/* global-settings.c generated by valac, the Vala compiler
 * generated from global-settings.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>


#define GNOMENU_TYPE_SETTINGS (gnomenu_settings_get_type ())
#define GNOMENU_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SETTINGS, GnomenuSettings))
#define GNOMENU_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_SETTINGS, GnomenuSettingsClass))
#define GNOMENU_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SETTINGS))
#define GNOMENU_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_SETTINGS))
#define GNOMENU_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_SETTINGS, GnomenuSettingsClass))

typedef struct _GnomenuSettings GnomenuSettings;
typedef struct _GnomenuSettingsClass GnomenuSettingsClass;
typedef struct _GnomenuSettingsPrivate GnomenuSettingsPrivate;

#define GNOMENU_TYPE_GLOBAL_SETTINGS (gnomenu_global_settings_get_type ())
#define GNOMENU_GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettings))
#define GNOMENU_GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettingsClass))
#define GNOMENU_IS_GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS))
#define GNOMENU_IS_GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_GLOBAL_SETTINGS))
#define GNOMENU_GLOBAL_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettingsClass))

typedef struct _GnomenuGlobalSettings GnomenuGlobalSettings;
typedef struct _GnomenuGlobalSettingsClass GnomenuGlobalSettingsClass;
typedef struct _GnomenuGlobalSettingsPrivate GnomenuGlobalSettingsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GnomenuSettings {
	GObject parent_instance;
	GnomenuSettingsPrivate * priv;
	GKeyFile* keyfile;
};

struct _GnomenuSettingsClass {
	GObjectClass parent_class;
	void (*attach_to_window) (GnomenuSettings* self, GdkWindow* window);
	gboolean (*get_show_local_menu) (GnomenuSettings* self);
	void (*set_show_local_menu) (GnomenuSettings* self, gboolean value);
	gboolean (*get_show_menu_icons) (GnomenuSettings* self);
	void (*set_show_menu_icons) (GnomenuSettings* self, gboolean value);
	gint (*get_changed_notify_timeout) (GnomenuSettings* self);
	void (*set_changed_notify_timeout) (GnomenuSettings* self, gint value);
};

struct _GnomenuGlobalSettings {
	GnomenuSettings parent_instance;
	GnomenuGlobalSettingsPrivate * priv;
};

struct _GnomenuGlobalSettingsClass {
	GnomenuSettingsClass parent_class;
};

struct _GnomenuGlobalSettingsPrivate {
	GdkScreen* _screen;
};


static gpointer gnomenu_global_settings_parent_class = NULL;

GType gnomenu_settings_get_type (void) G_GNUC_CONST;
GType gnomenu_global_settings_get_type (void) G_GNUC_CONST;
#define GNOMENU_GLOBAL_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettingsPrivate))
enum  {
	GNOMENU_GLOBAL_SETTINGS_DUMMY_PROPERTY,
	GNOMENU_GLOBAL_SETTINGS_SCREEN
};
static GnomenuGlobalSettings* gnomenu_global_settings_new (GdkScreen* screen);
static GnomenuGlobalSettings* gnomenu_global_settings_construct (GType object_type, GdkScreen* screen);
GnomenuGlobalSettings* gnomenu_global_settings_get (GdkScreen* screen);
GnomenuSettings* gnomenu_settings_new (void);
GnomenuSettings* gnomenu_settings_construct (GType object_type);
void gnomenu_global_settings_attach_to_screen (GnomenuGlobalSettings* self, GdkScreen* screen);
static void gnomenu_global_settings_set_screen (GnomenuGlobalSettings* self, GdkScreen* value);
GdkScreen* gnomenu_global_settings_get_screen (GnomenuGlobalSettings* self);
void gnomenu_settings_attach_to_window (GnomenuSettings* self, GdkWindow* window);
static void gnomenu_global_settings_finalize (GObject* obj);
static void gnomenu_global_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void gnomenu_global_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GnomenuGlobalSettings* gnomenu_global_settings_get (GdkScreen* screen) {
	GnomenuGlobalSettings* result = NULL;
	GnomenuGlobalSettings* settings;
	g_return_val_if_fail (screen != NULL, NULL);
	settings = g_object_get_data ((GObject*) screen, "globalmenu-settings");
	if (settings != NULL) {
		result = _g_object_ref0 (settings);
		return result;
	}
	result = gnomenu_global_settings_new (screen);
	return result;
}


static GnomenuGlobalSettings* gnomenu_global_settings_construct (GType object_type, GdkScreen* screen) {
	GnomenuGlobalSettings * self;
	self = (GnomenuGlobalSettings*) gnomenu_settings_construct (object_type);
	gnomenu_global_settings_attach_to_screen (self, screen);
	g_object_set_data_full ((GObject*) screen, "globalmenu-settings", g_object_ref ((GObject*) self), g_object_unref);
	return self;
}


static GnomenuGlobalSettings* gnomenu_global_settings_new (GdkScreen* screen) {
	return gnomenu_global_settings_construct (GNOMENU_TYPE_GLOBAL_SETTINGS, screen);
}


void gnomenu_global_settings_attach_to_screen (GnomenuGlobalSettings* self, GdkScreen* screen) {
	g_return_if_fail (self != NULL);
	gnomenu_global_settings_set_screen (self, screen);
	if (self->priv->_screen == NULL) {
		gnomenu_settings_attach_to_window ((GnomenuSettings*) self, NULL);
	} else {
		gnomenu_settings_attach_to_window ((GnomenuSettings*) self, gdk_screen_get_root_window (self->priv->_screen));
	}
}


GdkScreen* gnomenu_global_settings_get_screen (GnomenuGlobalSettings* self) {
	GdkScreen* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_screen;
	return result;
}


static void gnomenu_global_settings_set_screen (GnomenuGlobalSettings* self, GdkScreen* value) {
	GdkScreen* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_screen = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_screen), _tmp0_);
	g_object_notify ((GObject *) self, "screen");
}


static void gnomenu_global_settings_class_init (GnomenuGlobalSettingsClass * klass) {
	gnomenu_global_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuGlobalSettingsPrivate));
	G_OBJECT_CLASS (klass)->get_property = gnomenu_global_settings_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomenu_global_settings_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_global_settings_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_SETTINGS_SCREEN, g_param_spec_object ("screen", "screen", "screen", GDK_TYPE_SCREEN, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void gnomenu_global_settings_instance_init (GnomenuGlobalSettings * self) {
	self->priv = GNOMENU_GLOBAL_SETTINGS_GET_PRIVATE (self);
}


static void gnomenu_global_settings_finalize (GObject* obj) {
	GnomenuGlobalSettings * self;
	self = GNOMENU_GLOBAL_SETTINGS (obj);
	_g_object_unref0 (self->priv->_screen);
	G_OBJECT_CLASS (gnomenu_global_settings_parent_class)->finalize (obj);
}


GType gnomenu_global_settings_get_type (void) {
	static volatile gsize gnomenu_global_settings_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_global_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuGlobalSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_global_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuGlobalSettings), 0, (GInstanceInitFunc) gnomenu_global_settings_instance_init, NULL };
		GType gnomenu_global_settings_type_id;
		gnomenu_global_settings_type_id = g_type_register_static (GNOMENU_TYPE_SETTINGS, "GnomenuGlobalSettings", &g_define_type_info, 0);
		g_once_init_leave (&gnomenu_global_settings_type_id__volatile, gnomenu_global_settings_type_id);
	}
	return gnomenu_global_settings_type_id__volatile;
}


static void gnomenu_global_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuGlobalSettings * self;
	self = GNOMENU_GLOBAL_SETTINGS (object);
	switch (property_id) {
		case GNOMENU_GLOBAL_SETTINGS_SCREEN:
		g_value_set_object (value, gnomenu_global_settings_get_screen (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomenu_global_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GnomenuGlobalSettings * self;
	self = GNOMENU_GLOBAL_SETTINGS (object);
	switch (property_id) {
		case GNOMENU_GLOBAL_SETTINGS_SCREEN:
		gnomenu_global_settings_set_screen (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




