/* local-settings.c generated by valac, the Vala compiler
 * generated from local-settings.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>


#define GNOMENU_TYPE_SETTINGS (gnomenu_settings_get_type ())
#define GNOMENU_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SETTINGS, GnomenuSettings))
#define GNOMENU_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_SETTINGS, GnomenuSettingsClass))
#define GNOMENU_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SETTINGS))
#define GNOMENU_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_SETTINGS))
#define GNOMENU_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_SETTINGS, GnomenuSettingsClass))

typedef struct _GnomenuSettings GnomenuSettings;
typedef struct _GnomenuSettingsClass GnomenuSettingsClass;
typedef struct _GnomenuSettingsPrivate GnomenuSettingsPrivate;

#define GNOMENU_TYPE_LOCAL_SETTINGS (gnomenu_local_settings_get_type ())
#define GNOMENU_LOCAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_LOCAL_SETTINGS, GnomenuLocalSettings))
#define GNOMENU_LOCAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_LOCAL_SETTINGS, GnomenuLocalSettingsClass))
#define GNOMENU_IS_LOCAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_LOCAL_SETTINGS))
#define GNOMENU_IS_LOCAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_LOCAL_SETTINGS))
#define GNOMENU_LOCAL_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_LOCAL_SETTINGS, GnomenuLocalSettingsClass))

typedef struct _GnomenuLocalSettings GnomenuLocalSettings;
typedef struct _GnomenuLocalSettingsClass GnomenuLocalSettingsClass;
typedef struct _GnomenuLocalSettingsPrivate GnomenuLocalSettingsPrivate;

#define GNOMENU_TYPE_GLOBAL_SETTINGS (gnomenu_global_settings_get_type ())
#define GNOMENU_GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettings))
#define GNOMENU_GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettingsClass))
#define GNOMENU_IS_GLOBAL_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS))
#define GNOMENU_IS_GLOBAL_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_GLOBAL_SETTINGS))
#define GNOMENU_GLOBAL_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_GLOBAL_SETTINGS, GnomenuGlobalSettingsClass))

typedef struct _GnomenuGlobalSettings GnomenuGlobalSettings;
typedef struct _GnomenuGlobalSettingsClass GnomenuGlobalSettingsClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GnomenuSettings {
	GObject parent_instance;
	GnomenuSettingsPrivate * priv;
	GKeyFile* keyfile;
};

struct _GnomenuSettingsClass {
	GObjectClass parent_class;
	void (*attach_to_window) (GnomenuSettings* self, GdkWindow* window);
	gboolean (*get_show_local_menu) (GnomenuSettings* self);
	void (*set_show_local_menu) (GnomenuSettings* self, gboolean value);
	gboolean (*get_show_menu_icons) (GnomenuSettings* self);
	void (*set_show_menu_icons) (GnomenuSettings* self, gboolean value);
	gint (*get_changed_notify_timeout) (GnomenuSettings* self);
	void (*set_changed_notify_timeout) (GnomenuSettings* self, gint value);
};

struct _GnomenuLocalSettings {
	GnomenuSettings parent_instance;
	GnomenuLocalSettingsPrivate * priv;
};

struct _GnomenuLocalSettingsClass {
	GnomenuSettingsClass parent_class;
};

struct _GnomenuLocalSettingsPrivate {
	GnomenuGlobalSettings* _global;
};


static gpointer gnomenu_local_settings_parent_class = NULL;

GType gnomenu_settings_get_type (void) G_GNUC_CONST;
GType gnomenu_local_settings_get_type (void) G_GNUC_CONST;
GType gnomenu_global_settings_get_type (void) G_GNUC_CONST;
#define GNOMENU_LOCAL_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_LOCAL_SETTINGS, GnomenuLocalSettingsPrivate))
enum  {
	GNOMENU_LOCAL_SETTINGS_DUMMY_PROPERTY,
	GNOMENU_LOCAL_SETTINGS_GLOBAL,
	GNOMENU_LOCAL_SETTINGS_SHOW_LOCAL_MENU,
	GNOMENU_LOCAL_SETTINGS_SHOW_MENU_ICONS,
	GNOMENU_LOCAL_SETTINGS_CHANGED_NOTIFY_TIMEOUT
};
GnomenuSettings* gnomenu_settings_new (void);
GnomenuSettings* gnomenu_settings_construct (GType object_type);
void gnomenu_settings_attach_to_window (GnomenuSettings* self, GdkWindow* window);
void gnomenu_settings_set_show_local_menu (GnomenuSettings* self, gboolean value);
GnomenuLocalSettings* gnomenu_local_settings_new (GdkWindow* window);
GnomenuLocalSettings* gnomenu_local_settings_construct (GType object_type, GdkWindow* window);
GnomenuGlobalSettings* gnomenu_global_settings_get (GdkScreen* screen);
static void gnomenu_local_settings_set_global (GnomenuLocalSettings* self, GnomenuGlobalSettings* value);
static void gnomenu_local_settings_real_attach_to_window (GnomenuSettings* base, GdkWindow* window);
GnomenuGlobalSettings* gnomenu_local_settings_get_global (GnomenuLocalSettings* self);
gboolean gnomenu_settings_get_show_local_menu (GnomenuSettings* self);
gboolean gnomenu_settings_get_show_menu_icons (GnomenuSettings* self);
void gnomenu_settings_set_show_menu_icons (GnomenuSettings* self, gboolean value);
gint gnomenu_settings_get_changed_notify_timeout (GnomenuSettings* self);
void gnomenu_settings_set_changed_notify_timeout (GnomenuSettings* self, gint value);
static void gnomenu_local_settings_finalize (GObject* obj);
static void gnomenu_local_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void gnomenu_local_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



GnomenuLocalSettings* gnomenu_local_settings_construct (GType object_type, GdkWindow* window) {
	GnomenuLocalSettings * self;
	self = (GnomenuLocalSettings*) gnomenu_settings_construct (object_type);
	gnomenu_settings_attach_to_window ((GnomenuSettings*) self, window);
	gnomenu_settings_set_show_local_menu ((GnomenuSettings*) self, FALSE);
	return self;
}


GnomenuLocalSettings* gnomenu_local_settings_new (GdkWindow* window) {
	return gnomenu_local_settings_construct (GNOMENU_TYPE_LOCAL_SETTINGS, window);
}


static void gnomenu_local_settings_real_attach_to_window (GnomenuSettings* base, GdkWindow* window) {
	GnomenuLocalSettings * self;
	self = (GnomenuLocalSettings*) base;
	GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->attach_to_window (GNOMENU_SETTINGS (self), window);
	if (window != NULL) {
		GnomenuGlobalSettings* _tmp0_;
		gnomenu_local_settings_set_global (self, _tmp0_ = gnomenu_global_settings_get (gdk_drawable_get_screen ((GdkDrawable*) window)));
		_g_object_unref0 (_tmp0_);
	}
}


GnomenuGlobalSettings* gnomenu_local_settings_get_global (GnomenuLocalSettings* self) {
	GnomenuGlobalSettings* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_global;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void gnomenu_local_settings_set_global (GnomenuLocalSettings* self, GnomenuGlobalSettings* value) {
	GnomenuGlobalSettings* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_global = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_global), _tmp0_);
	g_object_notify ((GObject *) self, "global");
}


static gboolean gnomenu_local_settings_real_get_show_local_menu (GnomenuSettings* base) {
	gboolean result;
	GnomenuLocalSettings* self;
	gboolean _tmp0_ = FALSE;
	self = (GnomenuLocalSettings*) base;
	if (self->priv->_global == NULL) {
		result = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_show_local_menu (GNOMENU_SETTINGS (self));
		return result;
	}
	if (gnomenu_settings_get_show_local_menu ((GnomenuSettings*) self->priv->_global)) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_show_local_menu (GNOMENU_SETTINGS (self));
	}
	result = _tmp0_;
	return result;
}


static void gnomenu_local_settings_real_set_show_local_menu (GnomenuSettings* base, gboolean value) {
	GnomenuLocalSettings* self;
	self = (GnomenuLocalSettings*) base;
	GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->set_show_local_menu (GNOMENU_SETTINGS (self), value);
	g_object_notify ((GObject *) self, "show-local-menu");
}


static gboolean gnomenu_local_settings_real_get_show_menu_icons (GnomenuSettings* base) {
	gboolean result;
	GnomenuLocalSettings* self;
	gboolean _tmp0_ = FALSE;
	self = (GnomenuLocalSettings*) base;
	if (self->priv->_global == NULL) {
		result = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_show_menu_icons (GNOMENU_SETTINGS (self));
		return result;
	}
	if (gnomenu_settings_get_show_menu_icons ((GnomenuSettings*) self->priv->_global)) {
		_tmp0_ = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_show_menu_icons (GNOMENU_SETTINGS (self));
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	return result;
}


static void gnomenu_local_settings_real_set_show_menu_icons (GnomenuSettings* base, gboolean value) {
	GnomenuLocalSettings* self;
	self = (GnomenuLocalSettings*) base;
	GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->set_show_menu_icons (GNOMENU_SETTINGS (self), value);
	g_object_notify ((GObject *) self, "show-menu-icons");
}


static gint gnomenu_local_settings_real_get_changed_notify_timeout (GnomenuSettings* base) {
	gint result;
	GnomenuLocalSettings* self;
	self = (GnomenuLocalSettings*) base;
	if (self->priv->_global == NULL) {
		result = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_changed_notify_timeout (GNOMENU_SETTINGS (self));
		return result;
	}
	if (gnomenu_settings_get_changed_notify_timeout ((GnomenuSettings*) self->priv->_global) < GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_changed_notify_timeout (GNOMENU_SETTINGS (self))) {
		result = gnomenu_settings_get_changed_notify_timeout ((GnomenuSettings*) self->priv->_global);
		return result;
	}
	result = GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->get_changed_notify_timeout (GNOMENU_SETTINGS (self));
	return result;
}


static void gnomenu_local_settings_real_set_changed_notify_timeout (GnomenuSettings* base, gint value) {
	GnomenuLocalSettings* self;
	self = (GnomenuLocalSettings*) base;
	GNOMENU_SETTINGS_CLASS (gnomenu_local_settings_parent_class)->set_changed_notify_timeout (GNOMENU_SETTINGS (self), value);
	g_object_notify ((GObject *) self, "changed-notify-timeout");
}


static void gnomenu_local_settings_class_init (GnomenuLocalSettingsClass * klass) {
	gnomenu_local_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuLocalSettingsPrivate));
	GNOMENU_SETTINGS_CLASS (klass)->attach_to_window = gnomenu_local_settings_real_attach_to_window;
	GNOMENU_SETTINGS_CLASS (klass)->get_show_local_menu = gnomenu_local_settings_real_get_show_local_menu;
	GNOMENU_SETTINGS_CLASS (klass)->set_show_local_menu = gnomenu_local_settings_real_set_show_local_menu;
	GNOMENU_SETTINGS_CLASS (klass)->get_show_menu_icons = gnomenu_local_settings_real_get_show_menu_icons;
	GNOMENU_SETTINGS_CLASS (klass)->set_show_menu_icons = gnomenu_local_settings_real_set_show_menu_icons;
	GNOMENU_SETTINGS_CLASS (klass)->get_changed_notify_timeout = gnomenu_local_settings_real_get_changed_notify_timeout;
	GNOMENU_SETTINGS_CLASS (klass)->set_changed_notify_timeout = gnomenu_local_settings_real_set_changed_notify_timeout;
	G_OBJECT_CLASS (klass)->get_property = gnomenu_local_settings_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomenu_local_settings_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_local_settings_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_LOCAL_SETTINGS_GLOBAL, g_param_spec_object ("global", "global", "global", GNOMENU_TYPE_GLOBAL_SETTINGS, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_override_property (G_OBJECT_CLASS (klass), GNOMENU_LOCAL_SETTINGS_SHOW_LOCAL_MENU, "show-local-menu");
	g_object_class_override_property (G_OBJECT_CLASS (klass), GNOMENU_LOCAL_SETTINGS_SHOW_MENU_ICONS, "show-menu-icons");
	g_object_class_override_property (G_OBJECT_CLASS (klass), GNOMENU_LOCAL_SETTINGS_CHANGED_NOTIFY_TIMEOUT, "changed-notify-timeout");
}


static void gnomenu_local_settings_instance_init (GnomenuLocalSettings * self) {
	self->priv = GNOMENU_LOCAL_SETTINGS_GET_PRIVATE (self);
}


static void gnomenu_local_settings_finalize (GObject* obj) {
	GnomenuLocalSettings * self;
	self = GNOMENU_LOCAL_SETTINGS (obj);
	_g_object_unref0 (self->priv->_global);
	G_OBJECT_CLASS (gnomenu_local_settings_parent_class)->finalize (obj);
}


GType gnomenu_local_settings_get_type (void) {
	static volatile gsize gnomenu_local_settings_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_local_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuLocalSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_local_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuLocalSettings), 0, (GInstanceInitFunc) gnomenu_local_settings_instance_init, NULL };
		GType gnomenu_local_settings_type_id;
		gnomenu_local_settings_type_id = g_type_register_static (GNOMENU_TYPE_SETTINGS, "GnomenuLocalSettings", &g_define_type_info, 0);
		g_once_init_leave (&gnomenu_local_settings_type_id__volatile, gnomenu_local_settings_type_id);
	}
	return gnomenu_local_settings_type_id__volatile;
}


static void gnomenu_local_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuLocalSettings * self;
	self = GNOMENU_LOCAL_SETTINGS (object);
	switch (property_id) {
		case GNOMENU_LOCAL_SETTINGS_GLOBAL:
		g_value_set_object (value, gnomenu_local_settings_get_global (self));
		break;
		case GNOMENU_LOCAL_SETTINGS_SHOW_LOCAL_MENU:
		g_value_set_boolean (value, gnomenu_settings_get_show_local_menu ((GnomenuSettings*) self));
		break;
		case GNOMENU_LOCAL_SETTINGS_SHOW_MENU_ICONS:
		g_value_set_boolean (value, gnomenu_settings_get_show_menu_icons ((GnomenuSettings*) self));
		break;
		case GNOMENU_LOCAL_SETTINGS_CHANGED_NOTIFY_TIMEOUT:
		g_value_set_int (value, gnomenu_settings_get_changed_notify_timeout ((GnomenuSettings*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomenu_local_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GnomenuLocalSettings * self;
	self = GNOMENU_LOCAL_SETTINGS (object);
	switch (property_id) {
		case GNOMENU_LOCAL_SETTINGS_GLOBAL:
		gnomenu_local_settings_set_global (self, g_value_get_object (value));
		break;
		case GNOMENU_LOCAL_SETTINGS_SHOW_LOCAL_MENU:
		gnomenu_settings_set_show_local_menu ((GnomenuSettings*) self, g_value_get_boolean (value));
		break;
		case GNOMENU_LOCAL_SETTINGS_SHOW_MENU_ICONS:
		gnomenu_settings_set_show_menu_icons ((GnomenuSettings*) self, g_value_get_boolean (value));
		break;
		case GNOMENU_LOCAL_SETTINGS_CHANGED_NOTIFY_TIMEOUT:
		gnomenu_settings_set_changed_notify_timeout ((GnomenuSettings*) self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




