/* keygrab.c generated by valac, the Vala compiler
 * generated from keygrab.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>




gboolean gnomenu_grab_key (GdkWindow* grab_window, guint keyval, GdkModifierType state);
gboolean gnomenu_ungrab_key (GdkWindow* grab_window, guint keyval, GdkModifierType state);





