/* mnemonickeys.c generated by valac, the Vala compiler
 * generated from mnemonickeys.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gobject/gvaluecollector.h>


#define GNOMENU_TYPE_MNEMONIC_KEYS (gnomenu_mnemonic_keys_get_type ())
#define GNOMENU_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeys))
#define GNOMENU_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))
#define GNOMENU_IS_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_IS_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_MNEMONIC_KEYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))

typedef struct _GnomenuMnemonicKeys GnomenuMnemonicKeys;
typedef struct _GnomenuMnemonicKeysClass GnomenuMnemonicKeysClass;
typedef struct _GnomenuMnemonicKeysPrivate GnomenuMnemonicKeysPrivate;

#define GNOMENU_TYPE_SHELL (gnomenu_shell_get_type ())
#define GNOMENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SHELL, GnomenuShell))
#define GNOMENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SHELL))
#define GNOMENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_SHELL, GnomenuShellIface))

typedef struct _GnomenuShell GnomenuShell;
typedef struct _GnomenuShellIface GnomenuShellIface;

#define GNOMENU_TYPE_ITEM (gnomenu_item_get_type ())
#define GNOMENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ITEM, GnomenuItem))
#define GNOMENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ITEM))
#define GNOMENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_ITEM, GnomenuItemIface))

typedef struct _GnomenuItem GnomenuItem;
typedef struct _GnomenuItemIface GnomenuItemIface;

#define GNOMENU_TYPE_ITEM_TYPE (gnomenu_item_type_get_type ())

#define GNOMENU_TYPE_ITEM_STATE (gnomenu_item_state_get_type ())

#define GNOMENU_TYPE_WINDOW (gnomenu_window_get_type ())
#define GNOMENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindow))
#define GNOMENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))
#define GNOMENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_WINDOW))
#define GNOMENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_WINDOW))
#define GNOMENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))

typedef struct _GnomenuWindow GnomenuWindow;
typedef struct _GnomenuWindowClass GnomenuWindowClass;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GNOMENU_TYPE_MENU_ITEM (gnomenu_menu_item_get_type ())
#define GNOMENU_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItem))
#define GNOMENU_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItemClass))
#define GNOMENU_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MENU_ITEM))
#define GNOMENU_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MENU_ITEM))
#define GNOMENU_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItemClass))

typedef struct _GnomenuMenuItem GnomenuMenuItem;
typedef struct _GnomenuMenuItemClass GnomenuMenuItemClass;

#define GNOMENU_TYPE_MENU_LABEL (gnomenu_menu_label_get_type ())
#define GNOMENU_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MENU_LABEL, GnomenuMenuLabel))
#define GNOMENU_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MENU_LABEL, GnomenuMenuLabelClass))
#define GNOMENU_IS_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MENU_LABEL))
#define GNOMENU_IS_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MENU_LABEL))
#define GNOMENU_MENU_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MENU_LABEL, GnomenuMenuLabelClass))

typedef struct _GnomenuMenuLabel GnomenuMenuLabel;
typedef struct _GnomenuMenuLabelClass GnomenuMenuLabelClass;

#define GNOMENU_TYPE_ADAPTER (gnomenu_adapter_get_type ())
#define GNOMENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapter))
#define GNOMENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))
#define GNOMENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))

typedef struct _GnomenuAdapter GnomenuAdapter;
typedef struct _GnomenuAdapterClass GnomenuAdapterClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
typedef struct _GnomenuParamSpecMnemonicKeys GnomenuParamSpecMnemonicKeys;

struct _GnomenuMnemonicKeys {
	GTypeInstance parent_instance;
	volatile int ref_count;
	GnomenuMnemonicKeysPrivate * priv;
};

struct _GnomenuMnemonicKeysClass {
	GTypeClass parent_class;
	void (*finalize) (GnomenuMnemonicKeys *self);
};

typedef enum  {
	GNOMENU_ITEM_TYPE_NORMAL = 0,
	GNOMENU_ITEM_TYPE_CHECK = 1,
	GNOMENU_ITEM_TYPE_RADIO = 2,
	GNOMENU_ITEM_TYPE_IMAGE = 3,
	GNOMENU_ITEM_TYPE_SEPARATOR = 4,
	GNOMENU_ITEM_TYPE_ARROW = 5,
	GNOMENU_ITEM_TYPE_ICON = 6
} GnomenuItemType;

typedef enum  {
	GNOMENU_ITEM_STATE_UNTOGGLED = 0,
	GNOMENU_ITEM_STATE_TOGGLED = 1,
	GNOMENU_ITEM_STATE_TRISTATE = 2
} GnomenuItemState;

struct _GnomenuItemIface {
	GTypeInterface parent_iface;
	GnomenuShell* (*get_shell) (GnomenuItem* self);
	GnomenuShell* (*get_sub_shell) (GnomenuItem* self);
	gboolean (*get_has_sub_shell) (GnomenuItem* self);
	void (*set_has_sub_shell) (GnomenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (GnomenuItem* self);
	void (*set_client_side_sub_shell) (GnomenuItem* self, gboolean value);
	const char* (*get_item_id) (GnomenuItem* self);
	void (*set_item_id) (GnomenuItem* self, const char* value);
	GnomenuItemType (*get_item_type) (GnomenuItem* self);
	void (*set_item_type) (GnomenuItem* self, GnomenuItemType value);
	gboolean (*get_item_use_underline) (GnomenuItem* self);
	void (*set_item_use_underline) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (GnomenuItem* self);
	void (*set_item_sensitive) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_visible) (GnomenuItem* self);
	void (*set_item_visible) (GnomenuItem* self, gboolean value);
	GnomenuItemState (*get_item_state) (GnomenuItem* self);
	void (*set_item_state) (GnomenuItem* self, GnomenuItemState value);
	const char* (*get_item_label) (GnomenuItem* self);
	void (*set_item_label) (GnomenuItem* self, const char* value);
	const char* (*get_item_icon) (GnomenuItem* self);
	void (*set_item_icon) (GnomenuItem* self, const char* value);
	const char* (*get_item_accel_text) (GnomenuItem* self);
	void (*set_item_accel_text) (GnomenuItem* self, const char* value);
	const char* (*get_item_font) (GnomenuItem* self);
	void (*set_item_font) (GnomenuItem* self, const char* value);
};

struct _GnomenuShellIface {
	GTypeInterface parent_iface;
	GnomenuItem* (*get_item) (GnomenuShell* self, gint position);
	GnomenuItem* (*get_item_by_id) (GnomenuShell* self, const char* id);
	gint (*get_item_position) (GnomenuShell* self, GnomenuItem* item);
	GnomenuItem* (*get_owner) (GnomenuShell* self);
	gint (*get_length) (GnomenuShell* self);
	void (*set_length) (GnomenuShell* self, gint value);
};

struct _GnomenuMnemonicKeysPrivate {
	GHashTable* keys;
	GnomenuShell* _shell;
	GnomenuWindow* current_grab;
};

struct _GnomenuParamSpecMnemonicKeys {
	GParamSpec parent_instance;
};


static gpointer gnomenu_mnemonic_keys_parent_class = NULL;

gpointer gnomenu_mnemonic_keys_ref (gpointer instance);
void gnomenu_mnemonic_keys_unref (gpointer instance);
GParamSpec* gnomenu_param_spec_mnemonic_keys (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gnomenu_value_set_mnemonic_keys (GValue* value, gpointer v_object);
void gnomenu_value_take_mnemonic_keys (GValue* value, gpointer v_object);
gpointer gnomenu_value_get_mnemonic_keys (const GValue* value);
GType gnomenu_mnemonic_keys_get_type (void) G_GNUC_CONST;
GType gnomenu_item_type_get_type (void) G_GNUC_CONST;
GType gnomenu_item_state_get_type (void) G_GNUC_CONST;
GType gnomenu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_shell_get_type (void) G_GNUC_CONST;
GType gnomenu_window_get_type (void) G_GNUC_CONST;
#define GNOMENU_MNEMONIC_KEYS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysPrivate))
enum  {
	GNOMENU_MNEMONIC_KEYS_DUMMY_PROPERTY
};
static void gnomenu_mnemonic_keys_set_shell (GnomenuMnemonicKeys* self, GnomenuShell* value);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_new (GnomenuShell* shell);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_construct (GType object_type, GnomenuShell* shell);
void gnomenu_mnemonic_keys_ungrab (GnomenuMnemonicKeys* self);
GnomenuShell* gnomenu_mnemonic_keys_get_shell (GnomenuMnemonicKeys* self);
gint gnomenu_shell_get_length (GnomenuShell* self);
GnomenuItem* gnomenu_shell_get_item (GnomenuShell* self, gint position);
GType gnomenu_menu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_menu_label_get_type (void) G_GNUC_CONST;
guint gnomenu_menu_label_get_mnemonic_keyval (GnomenuMenuLabel* self);
const char* gnomenu_menu_label_get_label (GnomenuMenuLabel* self);
gboolean gnomenu_window_grab_key (GnomenuWindow* self, guint keyval, GdkModifierType state);
void gnomenu_window_set_key_widget (GnomenuWindow* self, GtkWidget* widget);
static GtkWidget* gnomenu_mnemonic_keys_get_toplevel (GnomenuMnemonicKeys* self);
void gnomenu_mnemonic_keys_grab (GnomenuMnemonicKeys* self, GnomenuWindow* window);
GType gnomenu_adapter_get_type (void) G_GNUC_CONST;
GtkMenuShell* gnomenu_adapter_get_gtk_shell (GnomenuAdapter* self);
gboolean gnomenu_window_ungrab_key (GnomenuWindow* self, guint keyval, GdkModifierType state);
static void gnomenu_mnemonic_keys_finalize (GnomenuMnemonicKeys* obj);



GnomenuMnemonicKeys* gnomenu_mnemonic_keys_construct (GType object_type, GnomenuShell* shell) {
	GnomenuMnemonicKeys* self;
	g_return_val_if_fail (shell != NULL, NULL);
	self = (GnomenuMnemonicKeys*) g_type_create_instance (object_type);
	gnomenu_mnemonic_keys_set_shell (self, shell);
	return self;
}


GnomenuMnemonicKeys* gnomenu_mnemonic_keys_new (GnomenuShell* shell) {
	return gnomenu_mnemonic_keys_construct (GNOMENU_TYPE_MNEMONIC_KEYS, shell);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void gnomenu_mnemonic_keys_grab (GnomenuMnemonicKeys* self, GnomenuWindow* window) {
	GdkModifierType mods;
	GnomenuWindow* _tmp3_;
	GtkWidget* _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	if (self->priv->current_grab != NULL) {
		gnomenu_mnemonic_keys_ungrab (self);
	}
	mods = GDK_MOD1_MASK;
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				GnomenuItem* _tmp1_;
				GnomenuMenuItem* item;
				GtkWidget* _tmp2_;
				GnomenuMenuLabel* label;
				guint keyval;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < gnomenu_shell_get_length (self->priv->_shell))) {
					break;
				}
				item = (_tmp1_ = gnomenu_shell_get_item (self->priv->_shell, i), GNOMENU_IS_MENU_ITEM (_tmp1_) ? ((GnomenuMenuItem*) _tmp1_) : NULL);
				if (item == NULL) {
					_g_object_unref0 (item);
					continue;
				}
				label = _g_object_ref0 ((_tmp2_ = gtk_bin_get_child ((GtkBin*) item), GNOMENU_IS_MENU_LABEL (_tmp2_) ? ((GnomenuMenuLabel*) _tmp2_) : NULL));
				if (label == NULL) {
					_g_object_unref0 (label);
					_g_object_unref0 (item);
					continue;
				}
				keyval = gnomenu_menu_label_get_mnemonic_keyval (label);
				g_debug ("mnemonickeys.vala:23: grabbing key for %s:%u", gnomenu_menu_label_get_label (label), keyval);
				gnomenu_window_grab_key (window, keyval, mods);
				gnomenu_window_grab_key (window, keyval, mods | GDK_MOD2_MASK);
				gnomenu_window_grab_key (window, keyval, mods | GDK_MOD3_MASK);
				gnomenu_window_grab_key (window, keyval, (mods | GDK_MOD3_MASK) | GDK_MOD2_MASK);
				g_hash_table_insert (self->priv->keys, GUINT_TO_POINTER (keyval), _g_object_ref0 ((GtkWidget*) item));
				_g_object_unref0 (label);
				_g_object_unref0 (item);
			}
		}
	}
	self->priv->current_grab = (_tmp3_ = _g_object_ref0 (window), _g_object_unref0 (self->priv->current_grab), _tmp3_);
	gnomenu_window_set_key_widget (self->priv->current_grab, _tmp4_ = gnomenu_mnemonic_keys_get_toplevel (self));
	_g_object_unref0 (_tmp4_);
}


static GtkWidget* gnomenu_mnemonic_keys_get_toplevel (GnomenuMnemonicKeys* self) {
	GtkWidget* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	if (GTK_IS_WIDGET (self->priv->_shell)) {
		GnomenuShell* _tmp0_;
		result = _g_object_ref0 (gtk_widget_get_toplevel ((_tmp0_ = self->priv->_shell, GTK_IS_WIDGET (_tmp0_) ? ((GtkWidget*) _tmp0_) : NULL)));
		return result;
	}
	if (GNOMENU_IS_ADAPTER (self->priv->_shell)) {
		GnomenuShell* _tmp1_;
		result = _g_object_ref0 (gtk_widget_get_toplevel ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((_tmp1_ = self->priv->_shell, GNOMENU_IS_ADAPTER (_tmp1_) ? ((GnomenuAdapter*) _tmp1_) : NULL))));
		return result;
	}
	result = NULL;
	return result;
}


void gnomenu_mnemonic_keys_ungrab (GnomenuMnemonicKeys* self) {
	GdkModifierType mods;
	GnomenuWindow* _tmp0_;
	g_return_if_fail (self != NULL);
	mods = GDK_MOD1_MASK;
	if (self->priv->current_grab != NULL) {
		{
			GList* keyval_collection;
			GList* keyval_it;
			keyval_collection = g_hash_table_get_keys (self->priv->keys);
			for (keyval_it = keyval_collection; keyval_it != NULL; keyval_it = keyval_it->next) {
				guint keyval;
				keyval = GPOINTER_TO_UINT (keyval_it->data);
				{
					g_debug ("mnemonickeys.vala:47: ungrabbing %u", keyval);
					gnomenu_window_ungrab_key (self->priv->current_grab, keyval, mods);
					gnomenu_window_ungrab_key (self->priv->current_grab, keyval, mods | GDK_MOD2_MASK);
					gnomenu_window_ungrab_key (self->priv->current_grab, keyval, mods | GDK_MOD3_MASK);
					gnomenu_window_ungrab_key (self->priv->current_grab, keyval, (mods | GDK_MOD3_MASK) | GDK_MOD2_MASK);
				}
			}
			_g_list_free0 (keyval_collection);
		}
		gnomenu_window_set_key_widget (self->priv->current_grab, NULL);
	}
	g_hash_table_remove_all (self->priv->keys);
	self->priv->current_grab = (_tmp0_ = NULL, _g_object_unref0 (self->priv->current_grab), _tmp0_);
}


GnomenuShell* gnomenu_mnemonic_keys_get_shell (GnomenuMnemonicKeys* self) {
	GnomenuShell* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_shell;
	return result;
}


static void gnomenu_mnemonic_keys_set_shell (GnomenuMnemonicKeys* self, GnomenuShell* value) {
	GnomenuShell* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_shell = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_shell), _tmp0_);
}


static void gnomenu_value_mnemonic_keys_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void gnomenu_value_mnemonic_keys_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		gnomenu_mnemonic_keys_unref (value->data[0].v_pointer);
	}
}


static void gnomenu_value_mnemonic_keys_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gnomenu_mnemonic_keys_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer gnomenu_value_mnemonic_keys_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* gnomenu_value_mnemonic_keys_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GnomenuMnemonicKeys* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gnomenu_mnemonic_keys_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* gnomenu_value_mnemonic_keys_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GnomenuMnemonicKeys** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gnomenu_mnemonic_keys_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* gnomenu_param_spec_mnemonic_keys (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GnomenuParamSpecMnemonicKeys* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GNOMENU_TYPE_MNEMONIC_KEYS), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer gnomenu_value_get_mnemonic_keys (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GNOMENU_TYPE_MNEMONIC_KEYS), NULL);
	return value->data[0].v_pointer;
}


void gnomenu_value_set_mnemonic_keys (GValue* value, gpointer v_object) {
	GnomenuMnemonicKeys* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GNOMENU_TYPE_MNEMONIC_KEYS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GNOMENU_TYPE_MNEMONIC_KEYS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gnomenu_mnemonic_keys_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gnomenu_mnemonic_keys_unref (old);
	}
}


void gnomenu_value_take_mnemonic_keys (GValue* value, gpointer v_object) {
	GnomenuMnemonicKeys* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GNOMENU_TYPE_MNEMONIC_KEYS));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GNOMENU_TYPE_MNEMONIC_KEYS));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gnomenu_mnemonic_keys_unref (old);
	}
}


static void gnomenu_mnemonic_keys_class_init (GnomenuMnemonicKeysClass * klass) {
	gnomenu_mnemonic_keys_parent_class = g_type_class_peek_parent (klass);
	GNOMENU_MNEMONIC_KEYS_CLASS (klass)->finalize = gnomenu_mnemonic_keys_finalize;
	g_type_class_add_private (klass, sizeof (GnomenuMnemonicKeysPrivate));
}


static void gnomenu_mnemonic_keys_instance_init (GnomenuMnemonicKeys * self) {
	self->priv = GNOMENU_MNEMONIC_KEYS_GET_PRIVATE (self);
	self->priv->keys = g_hash_table_new_full (g_direct_hash, g_direct_equal, NULL, g_object_unref);
	self->priv->current_grab = NULL;
	self->ref_count = 1;
}


static void gnomenu_mnemonic_keys_finalize (GnomenuMnemonicKeys* obj) {
	GnomenuMnemonicKeys * self;
	self = GNOMENU_MNEMONIC_KEYS (obj);
	_g_hash_table_unref0 (self->priv->keys);
	_g_object_unref0 (self->priv->_shell);
	_g_object_unref0 (self->priv->current_grab);
}


GType gnomenu_mnemonic_keys_get_type (void) {
	static volatile gsize gnomenu_mnemonic_keys_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_mnemonic_keys_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { gnomenu_value_mnemonic_keys_init, gnomenu_value_mnemonic_keys_free_value, gnomenu_value_mnemonic_keys_copy_value, gnomenu_value_mnemonic_keys_peek_pointer, "p", gnomenu_value_mnemonic_keys_collect_value, "p", gnomenu_value_mnemonic_keys_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuMnemonicKeysClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_mnemonic_keys_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuMnemonicKeys), 0, (GInstanceInitFunc) gnomenu_mnemonic_keys_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gnomenu_mnemonic_keys_type_id;
		gnomenu_mnemonic_keys_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GnomenuMnemonicKeys", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gnomenu_mnemonic_keys_type_id__volatile, gnomenu_mnemonic_keys_type_id);
	}
	return gnomenu_mnemonic_keys_type_id__volatile;
}


gpointer gnomenu_mnemonic_keys_ref (gpointer instance) {
	GnomenuMnemonicKeys* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void gnomenu_mnemonic_keys_unref (gpointer instance) {
	GnomenuMnemonicKeys* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GNOMENU_MNEMONIC_KEYS_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}




