/* adapter.c generated by valac, the Vala compiler
 * generated from adapter.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define GNOMENU_TYPE_SHELL (gnomenu_shell_get_type ())
#define GNOMENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SHELL, GnomenuShell))
#define GNOMENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SHELL))
#define GNOMENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_SHELL, GnomenuShellIface))

typedef struct _GnomenuShell GnomenuShell;
typedef struct _GnomenuShellIface GnomenuShellIface;

#define GNOMENU_TYPE_ITEM (gnomenu_item_get_type ())
#define GNOMENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ITEM, GnomenuItem))
#define GNOMENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ITEM))
#define GNOMENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_ITEM, GnomenuItemIface))

typedef struct _GnomenuItem GnomenuItem;
typedef struct _GnomenuItemIface GnomenuItemIface;

#define GNOMENU_TYPE_ITEM_TYPE (gnomenu_item_type_get_type ())

#define GNOMENU_TYPE_ITEM_STATE (gnomenu_item_state_get_type ())

#define GNOMENU_TYPE_ADAPTER (gnomenu_adapter_get_type ())
#define GNOMENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapter))
#define GNOMENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))
#define GNOMENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))

typedef struct _GnomenuAdapter GnomenuAdapter;
typedef struct _GnomenuAdapterClass GnomenuAdapterClass;
typedef struct _GnomenuAdapterPrivate GnomenuAdapterPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef enum  {
	GNOMENU_ITEM_TYPE_NORMAL = 0,
	GNOMENU_ITEM_TYPE_CHECK = 1,
	GNOMENU_ITEM_TYPE_RADIO = 2,
	GNOMENU_ITEM_TYPE_IMAGE = 3,
	GNOMENU_ITEM_TYPE_SEPARATOR = 4,
	GNOMENU_ITEM_TYPE_ARROW = 5,
	GNOMENU_ITEM_TYPE_ICON = 6
} GnomenuItemType;

typedef enum  {
	GNOMENU_ITEM_STATE_UNTOGGLED = 0,
	GNOMENU_ITEM_STATE_TOGGLED = 1,
	GNOMENU_ITEM_STATE_TRISTATE = 2
} GnomenuItemState;

struct _GnomenuItemIface {
	GTypeInterface parent_iface;
	GnomenuShell* (*get_shell) (GnomenuItem* self);
	GnomenuShell* (*get_sub_shell) (GnomenuItem* self);
	gboolean (*get_has_sub_shell) (GnomenuItem* self);
	void (*set_has_sub_shell) (GnomenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (GnomenuItem* self);
	void (*set_client_side_sub_shell) (GnomenuItem* self, gboolean value);
	const char* (*get_item_id) (GnomenuItem* self);
	void (*set_item_id) (GnomenuItem* self, const char* value);
	GnomenuItemType (*get_item_type) (GnomenuItem* self);
	void (*set_item_type) (GnomenuItem* self, GnomenuItemType value);
	gboolean (*get_item_use_underline) (GnomenuItem* self);
	void (*set_item_use_underline) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (GnomenuItem* self);
	void (*set_item_sensitive) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_visible) (GnomenuItem* self);
	void (*set_item_visible) (GnomenuItem* self, gboolean value);
	GnomenuItemState (*get_item_state) (GnomenuItem* self);
	void (*set_item_state) (GnomenuItem* self, GnomenuItemState value);
	const char* (*get_item_label) (GnomenuItem* self);
	void (*set_item_label) (GnomenuItem* self, const char* value);
	const char* (*get_item_icon) (GnomenuItem* self);
	void (*set_item_icon) (GnomenuItem* self, const char* value);
	const char* (*get_item_accel_text) (GnomenuItem* self);
	void (*set_item_accel_text) (GnomenuItem* self, const char* value);
	const char* (*get_item_font) (GnomenuItem* self);
	void (*set_item_font) (GnomenuItem* self, const char* value);
};

struct _GnomenuShellIface {
	GTypeInterface parent_iface;
	GnomenuItem* (*get_item) (GnomenuShell* self, gint position);
	GnomenuItem* (*get_item_by_id) (GnomenuShell* self, const char* id);
	gint (*get_item_position) (GnomenuShell* self, GnomenuItem* item);
	GnomenuItem* (*get_owner) (GnomenuShell* self);
	gint (*get_length) (GnomenuShell* self);
	void (*set_length) (GnomenuShell* self, gint value);
};

struct _GnomenuAdapter {
	GObject parent_instance;
	GnomenuAdapterPrivate * priv;
};

struct _GnomenuAdapterClass {
	GObjectClass parent_class;
};

struct _GnomenuAdapterPrivate {
	GtkMenuShell* _gtk_shell;
	gboolean disposed;
	gboolean _is_topmost;
};


static GHashTable* gnomenu_adapter_a2g;
static GHashTable* gnomenu_adapter_a2g = NULL;
static GHashTable* gnomenu_adapter_g2a;
static GHashTable* gnomenu_adapter_g2a = NULL;
static gpointer gnomenu_adapter_parent_class = NULL;
static GnomenuShellIface* gnomenu_adapter_gnomenu_shell_parent_iface = NULL;

GType gnomenu_item_type_get_type (void) G_GNUC_CONST;
GType gnomenu_item_state_get_type (void) G_GNUC_CONST;
GType gnomenu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_shell_get_type (void) G_GNUC_CONST;
GType gnomenu_adapter_get_type (void) G_GNUC_CONST;
#define GNOMENU_ADAPTER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_ADAPTER, GnomenuAdapterPrivate))
enum  {
	GNOMENU_ADAPTER_DUMMY_PROPERTY,
	GNOMENU_ADAPTER_GTK_SHELL,
	GNOMENU_ADAPTER_IS_TOPMOST,
	GNOMENU_ADAPTER_OWNER,
	GNOMENU_ADAPTER_LENGTH
};
void gnomenu_adapter_set_gtk_shell (GnomenuAdapter* self, GtkMenuShell* value);
GnomenuAdapter* gnomenu_adapter_new (GtkMenuShell* gtk_shell);
GnomenuAdapter* gnomenu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell);
GtkMenuShell* gnomenu_adapter_get_gtk_shell (GnomenuAdapter* self);
static void gnomenu_adapter_real_dispose (GObject* base);
GnomenuAdapter* gnomenu_adapter_get_adapter (GtkMenuShell* gtk_shell);
GtkMenuItem* gtk_menu_shell_get_item (GtkMenuShell* menu_shell, gint position);
static GnomenuItem* gnomenu_adapter_real_get_item (GnomenuShell* base, gint position);
gint gnomenu_shell_get_length (GnomenuShell* self);
GnomenuItem* gnomenu_shell_get_item (GnomenuShell* self, gint position);
const char* gnomenu_item_get_item_id (GnomenuItem* self);
static GnomenuItem* gnomenu_adapter_real_get_item_by_id (GnomenuShell* base, const char* id);
gint gtk_menu_shell_get_item_position (GtkMenuShell* menu_shell, GtkMenuItem* item);
static gint gnomenu_adapter_real_get_item_position (GnomenuShell* base, GnomenuItem* item);
gboolean gnomenu_adapter_get_is_topmost (GnomenuAdapter* self);
void gnomenu_adapter_set_is_topmost (GnomenuAdapter* self, gboolean value);
gint gtk_menu_shell_get_length (GtkMenuShell* menushell);
void gtk_menu_shell_set_length (GtkMenuShell* menushell, gint length);
static GObject * gnomenu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void gnomenu_adapter_finalize (GObject* obj);
GnomenuItem* gnomenu_shell_get_owner (GnomenuShell* self);
static void gnomenu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void gnomenu_shell_set_length (GnomenuShell* self, gint value);
static void gnomenu_adapter_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



GnomenuAdapter* gnomenu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell) {
	GParameter * __params;
	GParameter * __params_it;
	GnomenuAdapter * self;
	g_return_val_if_fail (gtk_shell != NULL, NULL);
	__params = g_new0 (GParameter, 1);
	__params_it = __params;
	__params_it->name = "gtk-shell";
	g_value_init (&__params_it->value, GTK_TYPE_MENU_SHELL);
	g_value_set_object (&__params_it->value, gtk_shell);
	__params_it++;
	self = g_object_newv (object_type, __params_it - __params, __params);
	while (__params_it > __params) {
		--__params_it;
		g_value_unset (&__params_it->value);
	}
	g_free (__params);
	return self;
}


GnomenuAdapter* gnomenu_adapter_new (GtkMenuShell* gtk_shell) {
	return gnomenu_adapter_construct (GNOMENU_TYPE_ADAPTER, gtk_shell);
}


static void gnomenu_adapter_real_dispose (GObject* base) {
	GnomenuAdapter * self;
	self = (GnomenuAdapter*) base;
	if (!self->priv->disposed) {
		g_hash_table_remove (gnomenu_adapter_a2g, self);
		g_hash_table_remove (gnomenu_adapter_g2a, self->priv->_gtk_shell);
		self->priv->disposed = TRUE;
	}
	G_OBJECT_CLASS (gnomenu_adapter_parent_class)->dispose (G_OBJECT (self));
}


GnomenuAdapter* gnomenu_adapter_get_adapter (GtkMenuShell* gtk_shell) {
	GnomenuAdapter* result = NULL;
	GnomenuAdapter* a;
	g_return_val_if_fail (gtk_shell != NULL, NULL);
	if (gnomenu_adapter_g2a == NULL) {
		result = NULL;
		return result;
	}
	a = (GnomenuAdapter*) g_hash_table_lookup (gnomenu_adapter_g2a, gtk_shell);
	result = a;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static GnomenuItem* gnomenu_adapter_real_get_item (GnomenuShell* base, gint position) {
	GnomenuAdapter * self;
	GnomenuItem* result = NULL;
	GtkMenuItem* _tmp0_;
	self = (GnomenuAdapter*) base;
	result = _g_object_ref0 ((_tmp0_ = gtk_menu_shell_get_item (self->priv->_gtk_shell, position), GNOMENU_IS_ITEM (_tmp0_) ? ((GnomenuItem*) _tmp0_) : NULL));
	return result;
}


static GnomenuItem* gnomenu_adapter_real_get_item_by_id (GnomenuShell* base, const char* id) {
	GnomenuAdapter * self;
	GnomenuItem* result = NULL;
	gint length;
	self = (GnomenuAdapter*) base;
	g_return_val_if_fail (id != NULL, NULL);
	length = gnomenu_shell_get_length ((GnomenuShell*) self);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				GnomenuItem* item;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < length)) {
					break;
				}
				item = gnomenu_shell_get_item ((GnomenuShell*) self, i);
				if (_vala_strcmp0 (gnomenu_item_get_item_id (item), id) == 0) {
					result = item;
					return result;
				}
				_g_object_unref0 (item);
			}
		}
	}
	result = NULL;
	return result;
}


static gint gnomenu_adapter_real_get_item_position (GnomenuShell* base, GnomenuItem* item) {
	GnomenuAdapter * self;
	gint result = 0;
	self = (GnomenuAdapter*) base;
	g_return_val_if_fail (item != NULL, 0);
	result = gtk_menu_shell_get_item_position (self->priv->_gtk_shell, (GtkMenuItem*) item);
	return result;
}


GtkMenuShell* gnomenu_adapter_get_gtk_shell (GnomenuAdapter* self) {
	GtkMenuShell* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_gtk_shell;
	return result;
}


void gnomenu_adapter_set_gtk_shell (GnomenuAdapter* self, GtkMenuShell* value) {
	GtkMenuShell* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_gtk_shell = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_gtk_shell), _tmp0_);
	g_object_notify ((GObject *) self, "gtk-shell");
}


gboolean gnomenu_adapter_get_is_topmost (GnomenuAdapter* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_is_topmost;
	return result;
}


void gnomenu_adapter_set_is_topmost (GnomenuAdapter* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_is_topmost = value;
	g_object_notify ((GObject *) self, "is-topmost");
}


static GnomenuItem* gnomenu_adapter_real_get_owner (GnomenuShell* base) {
	GnomenuItem* result;
	GnomenuAdapter* self;
	self = (GnomenuAdapter*) base;
	if (self->priv->_is_topmost) {
		result = NULL;
		return result;
	}
	if (GTK_IS_MENU_BAR (self->priv->_gtk_shell)) {
		result = NULL;
		return result;
	}
	if (GTK_IS_MENU (self->priv->_gtk_shell)) {
		GtkMenuShell* _tmp0_;
		GtkWidget* _tmp1_;
		result = (_tmp1_ = gtk_menu_get_attach_widget ((_tmp0_ = self->priv->_gtk_shell, GTK_IS_MENU (_tmp0_) ? ((GtkMenu*) _tmp0_) : NULL)), GNOMENU_IS_ITEM (_tmp1_) ? ((GnomenuItem*) _tmp1_) : NULL);
		return result;
	}
	result = NULL;
	return result;
}


static gint gnomenu_adapter_real_get_length (GnomenuShell* base) {
	gint result;
	GnomenuAdapter* self;
	self = (GnomenuAdapter*) base;
	result = gtk_menu_shell_get_length (self->priv->_gtk_shell);
	return result;
}


static void gnomenu_adapter_real_set_length (GnomenuShell* base, gint value) {
	GnomenuAdapter* self;
	self = (GnomenuAdapter*) base;
	gtk_menu_shell_set_length (self->priv->_gtk_shell, value);
	g_object_notify ((GObject *) self, "length");
}


static GObject * gnomenu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GnomenuAdapter * self;
	parent_class = G_OBJECT_CLASS (gnomenu_adapter_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = GNOMENU_ADAPTER (obj);
	{
		g_hash_table_insert (gnomenu_adapter_a2g, self, _g_object_ref0 (self->priv->_gtk_shell));
		g_hash_table_insert (gnomenu_adapter_g2a, _g_object_ref0 (self->priv->_gtk_shell), self);
	}
	return obj;
}


static void gnomenu_adapter_class_init (GnomenuAdapterClass * klass) {
	gnomenu_adapter_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuAdapterPrivate));
	G_OBJECT_CLASS (klass)->dispose = gnomenu_adapter_real_dispose;
	G_OBJECT_CLASS (klass)->get_property = gnomenu_adapter_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomenu_adapter_set_property;
	G_OBJECT_CLASS (klass)->constructor = gnomenu_adapter_constructor;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_adapter_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_ADAPTER_GTK_SHELL, g_param_spec_object ("gtk-shell", "gtk-shell", "gtk-shell", GTK_TYPE_MENU_SHELL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_ADAPTER_IS_TOPMOST, g_param_spec_boolean ("is-topmost", "is-topmost", "is-topmost", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_override_property (G_OBJECT_CLASS (klass), GNOMENU_ADAPTER_OWNER, "owner");
	g_object_class_override_property (G_OBJECT_CLASS (klass), GNOMENU_ADAPTER_LENGTH, "length");
	gnomenu_adapter_a2g = g_hash_table_new_full (g_direct_hash, g_direct_equal, NULL, g_object_unref);
	gnomenu_adapter_g2a = g_hash_table_new_full (g_direct_hash, g_direct_equal, g_object_unref, NULL);
}


static void gnomenu_adapter_gnomenu_shell_interface_init (GnomenuShellIface * iface) {
	gnomenu_adapter_gnomenu_shell_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_item = gnomenu_adapter_real_get_item;
	iface->get_item_by_id = gnomenu_adapter_real_get_item_by_id;
	iface->get_item_position = gnomenu_adapter_real_get_item_position;
	iface->get_owner = gnomenu_adapter_real_get_owner;
	iface->get_length = gnomenu_adapter_real_get_length;
	iface->set_length = gnomenu_adapter_real_set_length;
}


static void gnomenu_adapter_instance_init (GnomenuAdapter * self) {
	self->priv = GNOMENU_ADAPTER_GET_PRIVATE (self);
	self->priv->disposed = FALSE;
	self->priv->_is_topmost = FALSE;
}


static void gnomenu_adapter_finalize (GObject* obj) {
	GnomenuAdapter * self;
	self = GNOMENU_ADAPTER (obj);
	_g_object_unref0 (self->priv->_gtk_shell);
	G_OBJECT_CLASS (gnomenu_adapter_parent_class)->finalize (obj);
}


GType gnomenu_adapter_get_type (void) {
	static volatile gsize gnomenu_adapter_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_adapter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuAdapterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_adapter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuAdapter), 0, (GInstanceInitFunc) gnomenu_adapter_instance_init, NULL };
		static const GInterfaceInfo gnomenu_shell_info = { (GInterfaceInitFunc) gnomenu_adapter_gnomenu_shell_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType gnomenu_adapter_type_id;
		gnomenu_adapter_type_id = g_type_register_static (G_TYPE_OBJECT, "GnomenuAdapter", &g_define_type_info, 0);
		g_type_add_interface_static (gnomenu_adapter_type_id, GNOMENU_TYPE_SHELL, &gnomenu_shell_info);
		g_once_init_leave (&gnomenu_adapter_type_id__volatile, gnomenu_adapter_type_id);
	}
	return gnomenu_adapter_type_id__volatile;
}


static void gnomenu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuAdapter * self;
	self = GNOMENU_ADAPTER (object);
	switch (property_id) {
		case GNOMENU_ADAPTER_GTK_SHELL:
		g_value_set_object (value, gnomenu_adapter_get_gtk_shell (self));
		break;
		case GNOMENU_ADAPTER_IS_TOPMOST:
		g_value_set_boolean (value, gnomenu_adapter_get_is_topmost (self));
		break;
		case GNOMENU_ADAPTER_OWNER:
		g_value_set_object (value, gnomenu_shell_get_owner ((GnomenuShell*) self));
		break;
		case GNOMENU_ADAPTER_LENGTH:
		g_value_set_int (value, gnomenu_shell_get_length ((GnomenuShell*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomenu_adapter_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GnomenuAdapter * self;
	self = GNOMENU_ADAPTER (object);
	switch (property_id) {
		case GNOMENU_ADAPTER_GTK_SHELL:
		gnomenu_adapter_set_gtk_shell (self, g_value_get_object (value));
		break;
		case GNOMENU_ADAPTER_IS_TOPMOST:
		gnomenu_adapter_set_is_topmost (self, g_value_get_boolean (value));
		break;
		case GNOMENU_ADAPTER_LENGTH:
		gnomenu_shell_set_length ((GnomenuShell*) self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




