/* globalmenuadapter.c generated by valac, the Vala compiler
 * generated from globalmenuadapter.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define GNOMENU_TYPE_SHELL (gnomenu_shell_get_type ())
#define GNOMENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SHELL, GnomenuShell))
#define GNOMENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SHELL))
#define GNOMENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_SHELL, GnomenuShellIface))

typedef struct _GnomenuShell GnomenuShell;
typedef struct _GnomenuShellIface GnomenuShellIface;

#define GNOMENU_TYPE_ITEM (gnomenu_item_get_type ())
#define GNOMENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ITEM, GnomenuItem))
#define GNOMENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ITEM))
#define GNOMENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_ITEM, GnomenuItemIface))

typedef struct _GnomenuItem GnomenuItem;
typedef struct _GnomenuItemIface GnomenuItemIface;

#define GNOMENU_TYPE_ITEM_TYPE (gnomenu_item_type_get_type ())

#define GNOMENU_TYPE_ITEM_STATE (gnomenu_item_state_get_type ())

#define GNOMENU_TYPE_ADAPTER (gnomenu_adapter_get_type ())
#define GNOMENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapter))
#define GNOMENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))
#define GNOMENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_ADAPTER))
#define GNOMENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_ADAPTER, GnomenuAdapterClass))

typedef struct _GnomenuAdapter GnomenuAdapter;
typedef struct _GnomenuAdapterClass GnomenuAdapterClass;
typedef struct _GnomenuAdapterPrivate GnomenuAdapterPrivate;

#define GNOMENU_TYPE_GLOBAL_MENU_ADAPTER (gnomenu_global_menu_adapter_get_type ())
#define GNOMENU_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, GnomenuGlobalMenuAdapter))
#define GNOMENU_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, GnomenuGlobalMenuAdapterClass))
#define GNOMENU_IS_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER))
#define GNOMENU_IS_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER))
#define GNOMENU_GLOBAL_MENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, GnomenuGlobalMenuAdapterClass))

typedef struct _GnomenuGlobalMenuAdapter GnomenuGlobalMenuAdapter;
typedef struct _GnomenuGlobalMenuAdapterClass GnomenuGlobalMenuAdapterClass;
typedef struct _GnomenuGlobalMenuAdapterPrivate GnomenuGlobalMenuAdapterPrivate;

#define GNOMENU_TYPE_MONITOR (gnomenu_monitor_get_type ())
#define GNOMENU_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitor))
#define GNOMENU_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))
#define GNOMENU_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MONITOR))
#define GNOMENU_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MONITOR))
#define GNOMENU_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))

typedef struct _GnomenuMonitor GnomenuMonitor;
typedef struct _GnomenuMonitorClass GnomenuMonitorClass;

#define GNOMENU_TYPE_MNEMONIC_KEYS (gnomenu_mnemonic_keys_get_type ())
#define GNOMENU_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeys))
#define GNOMENU_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))
#define GNOMENU_IS_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_IS_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_MNEMONIC_KEYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))

typedef struct _GnomenuMnemonicKeys GnomenuMnemonicKeys;
typedef struct _GnomenuMnemonicKeysClass GnomenuMnemonicKeysClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gnomenu_mnemonic_keys_unref0(var) ((var == NULL) ? NULL : (var = (gnomenu_mnemonic_keys_unref (var), NULL)))

#define GNOMENU_TYPE_WINDOW (gnomenu_window_get_type ())
#define GNOMENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindow))
#define GNOMENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))
#define GNOMENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_WINDOW))
#define GNOMENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_WINDOW))
#define GNOMENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))

typedef struct _GnomenuWindow GnomenuWindow;
typedef struct _GnomenuWindowClass GnomenuWindowClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))

typedef enum  {
	GNOMENU_ITEM_TYPE_NORMAL = 0,
	GNOMENU_ITEM_TYPE_CHECK = 1,
	GNOMENU_ITEM_TYPE_RADIO = 2,
	GNOMENU_ITEM_TYPE_IMAGE = 3,
	GNOMENU_ITEM_TYPE_SEPARATOR = 4,
	GNOMENU_ITEM_TYPE_ARROW = 5,
	GNOMENU_ITEM_TYPE_ICON = 6
} GnomenuItemType;

typedef enum  {
	GNOMENU_ITEM_STATE_UNTOGGLED = 0,
	GNOMENU_ITEM_STATE_TOGGLED = 1,
	GNOMENU_ITEM_STATE_TRISTATE = 2
} GnomenuItemState;

struct _GnomenuItemIface {
	GTypeInterface parent_iface;
	GnomenuShell* (*get_shell) (GnomenuItem* self);
	GnomenuShell* (*get_sub_shell) (GnomenuItem* self);
	gboolean (*get_has_sub_shell) (GnomenuItem* self);
	void (*set_has_sub_shell) (GnomenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (GnomenuItem* self);
	void (*set_client_side_sub_shell) (GnomenuItem* self, gboolean value);
	const char* (*get_item_id) (GnomenuItem* self);
	void (*set_item_id) (GnomenuItem* self, const char* value);
	GnomenuItemType (*get_item_type) (GnomenuItem* self);
	void (*set_item_type) (GnomenuItem* self, GnomenuItemType value);
	gboolean (*get_item_use_underline) (GnomenuItem* self);
	void (*set_item_use_underline) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (GnomenuItem* self);
	void (*set_item_sensitive) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_visible) (GnomenuItem* self);
	void (*set_item_visible) (GnomenuItem* self, gboolean value);
	GnomenuItemState (*get_item_state) (GnomenuItem* self);
	void (*set_item_state) (GnomenuItem* self, GnomenuItemState value);
	const char* (*get_item_label) (GnomenuItem* self);
	void (*set_item_label) (GnomenuItem* self, const char* value);
	const char* (*get_item_icon) (GnomenuItem* self);
	void (*set_item_icon) (GnomenuItem* self, const char* value);
	const char* (*get_item_accel_text) (GnomenuItem* self);
	void (*set_item_accel_text) (GnomenuItem* self, const char* value);
	const char* (*get_item_font) (GnomenuItem* self);
	void (*set_item_font) (GnomenuItem* self, const char* value);
};

struct _GnomenuShellIface {
	GTypeInterface parent_iface;
	GnomenuItem* (*get_item) (GnomenuShell* self, gint position);
	GnomenuItem* (*get_item_by_id) (GnomenuShell* self, const char* id);
	gint (*get_item_position) (GnomenuShell* self, GnomenuItem* item);
	GnomenuItem* (*get_owner) (GnomenuShell* self);
	gint (*get_length) (GnomenuShell* self);
	void (*set_length) (GnomenuShell* self, gint value);
};

struct _GnomenuAdapter {
	GObject parent_instance;
	GnomenuAdapterPrivate * priv;
};

struct _GnomenuAdapterClass {
	GObjectClass parent_class;
};

struct _GnomenuGlobalMenuAdapter {
	GnomenuAdapter parent_instance;
	GnomenuGlobalMenuAdapterPrivate * priv;
};

struct _GnomenuGlobalMenuAdapterClass {
	GnomenuAdapterClass parent_class;
};

struct _GnomenuGlobalMenuAdapterPrivate {
	GnomenuMonitor* active_window_monitor;
	GnomenuMnemonicKeys* mnemonic_keys;
};


static gpointer gnomenu_global_menu_adapter_parent_class = NULL;

GType gnomenu_item_type_get_type (void) G_GNUC_CONST;
GType gnomenu_item_state_get_type (void) G_GNUC_CONST;
GType gnomenu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_shell_get_type (void) G_GNUC_CONST;
GType gnomenu_adapter_get_type (void) G_GNUC_CONST;
GType gnomenu_global_menu_adapter_get_type (void) G_GNUC_CONST;
GType gnomenu_monitor_get_type (void) G_GNUC_CONST;
gpointer gnomenu_mnemonic_keys_ref (gpointer instance);
void gnomenu_mnemonic_keys_unref (gpointer instance);
GParamSpec* gnomenu_param_spec_mnemonic_keys (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gnomenu_value_set_mnemonic_keys (GValue* value, gpointer v_object);
void gnomenu_value_take_mnemonic_keys (GValue* value, gpointer v_object);
gpointer gnomenu_value_get_mnemonic_keys (const GValue* value);
GType gnomenu_mnemonic_keys_get_type (void) G_GNUC_CONST;
#define GNOMENU_GLOBAL_MENU_ADAPTER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, GnomenuGlobalMenuAdapterPrivate))
enum  {
	GNOMENU_GLOBAL_MENU_ADAPTER_DUMMY_PROPERTY,
	GNOMENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW
};
void gnomenu_adapter_set_gtk_shell (GnomenuAdapter* self, GtkMenuShell* value);
GnomenuGlobalMenuAdapter* gnomenu_global_menu_adapter_new (GtkMenuShell* gtk_shell);
GnomenuGlobalMenuAdapter* gnomenu_global_menu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell);
GType gnomenu_window_get_type (void) G_GNUC_CONST;
void gnomenu_mnemonic_keys_grab (GnomenuMnemonicKeys* self, GnomenuWindow* window);
GnomenuWindow* gnomenu_global_menu_adapter_get_active_window (GnomenuGlobalMenuAdapter* self);
static void gnomenu_global_menu_adapter_regrab_mnemonic_keys (GnomenuGlobalMenuAdapter* self);
static void gnomenu_global_menu_adapter_emit_active_window_changed (GnomenuGlobalMenuAdapter* self, GnomenuWindow* prev_window);
void gnomenu_window_emit_menu_event (GnomenuWindow* self, const char* path);
char* gnomenu_item_get_item_path (GnomenuItem* self);
static void gnomenu_global_menu_adapter_item_activated (GnomenuGlobalMenuAdapter* self, GnomenuItem* item);
void gnomenu_window_emit_menu_select (GnomenuWindow* self, const char* path, const char* pos);
static void gnomenu_global_menu_adapter_item_selected (GnomenuGlobalMenuAdapter* self, GnomenuItem* item);
void gnomenu_window_emit_menu_deselect (GnomenuWindow* self, const char* path);
static void gnomenu_global_menu_adapter_item_deselected (GnomenuGlobalMenuAdapter* self, GnomenuItem* item);
GtkMenuShell* gnomenu_adapter_get_gtk_shell (GnomenuAdapter* self);
static gboolean gnomenu_global_menu_adapter_sync_monitor_num (GnomenuGlobalMenuAdapter* self);
static gboolean _gnomenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self);
static void _gnomenu_global_menu_adapter_hierarchy_changed (GnomenuGlobalMenuAdapter* self, GtkWidget* old_toplevel);
void gnomenu_monitor_set_monitor_num (GnomenuMonitor* self, gint value);
static void gnomenu_global_menu_adapter_chainup_key_changed (GnomenuGlobalMenuAdapter* self, GtkWindow* window);
static void _gnomenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self);
static void _gnomenu_global_menu_adapter_hierarchy_changed_chain_keys (GnomenuGlobalMenuAdapter* self, GtkWidget* old_toplevel);
GnomenuWindow* gnomenu_monitor_get_active_window (GnomenuMonitor* self);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_new (GnomenuShell* shell);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_construct (GType object_type, GnomenuShell* shell);
GnomenuMonitor* gnomenu_monitor_new (GdkScreen* screen);
GnomenuMonitor* gnomenu_monitor_construct (GType object_type, GdkScreen* screen);
void gnomenu_monitor_set_managed_shell (GnomenuMonitor* self, GnomenuShell* value);
static void _gnomenu_global_menu_adapter_emit_active_window_changed_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self);
static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self);
static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_adapter_item_activated_gnomenu_shell_activate (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self);
static void _gnomenu_global_menu_adapter_item_selected_gnomenu_shell_select (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self);
static void _gnomenu_global_menu_adapter_item_deselected_gnomenu_shell_deselect (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self);
static void __gnomenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self);
static void __gnomenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self);
static GObject * gnomenu_global_menu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void gnomenu_global_menu_adapter_finalize (GObject* obj);
static void gnomenu_global_menu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



GnomenuGlobalMenuAdapter* gnomenu_global_menu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell) {
	GParameter * __params;
	GParameter * __params_it;
	GnomenuGlobalMenuAdapter * self;
	g_return_val_if_fail (gtk_shell != NULL, NULL);
	__params = g_new0 (GParameter, 1);
	__params_it = __params;
	__params_it->name = "gtk-shell";
	g_value_init (&__params_it->value, GTK_TYPE_MENU_SHELL);
	g_value_set_object (&__params_it->value, gtk_shell);
	__params_it++;
	self = g_object_newv (object_type, __params_it - __params, __params);
	while (__params_it > __params) {
		--__params_it;
		g_value_unset (&__params_it->value);
	}
	g_free (__params);
	return self;
}


GnomenuGlobalMenuAdapter* gnomenu_global_menu_adapter_new (GtkMenuShell* gtk_shell) {
	return gnomenu_global_menu_adapter_construct (GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, gtk_shell);
}


static void gnomenu_global_menu_adapter_regrab_mnemonic_keys (GnomenuGlobalMenuAdapter* self) {
	g_return_if_fail (self != NULL);
	gnomenu_mnemonic_keys_grab (self->priv->mnemonic_keys, gnomenu_global_menu_adapter_get_active_window (self));
}


static void gnomenu_global_menu_adapter_emit_active_window_changed (GnomenuGlobalMenuAdapter* self, GnomenuWindow* prev_window) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "active-window-changed", prev_window);
}


static void gnomenu_global_menu_adapter_item_activated (GnomenuGlobalMenuAdapter* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_event (gnomenu_global_menu_adapter_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static void gnomenu_global_menu_adapter_item_selected (GnomenuGlobalMenuAdapter* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_select (gnomenu_global_menu_adapter_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item), NULL);
		_g_free0 (_tmp0_);
	}
}


static void gnomenu_global_menu_adapter_item_deselected (GnomenuGlobalMenuAdapter* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_deselect (gnomenu_global_menu_adapter_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _gnomenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self) {
	gboolean result;
	result = gnomenu_global_menu_adapter_sync_monitor_num (self);
	return result;
}


static void _gnomenu_global_menu_adapter_hierarchy_changed (GnomenuGlobalMenuAdapter* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self)), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWidget*) toplevel, "configure-event", (GCallback) _gnomenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event, self, 0);
	}
	if (old_toplevel != NULL) {
		guint _tmp1_;
		g_signal_parse_name ("configure-event", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (old_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _gnomenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event, self);
	}
	_g_object_unref0 (toplevel);
}


static gboolean gnomenu_global_menu_adapter_sync_monitor_num (GnomenuGlobalMenuAdapter* self) {
	gboolean result = FALSE;
	GdkScreen* screen;
	g_return_val_if_fail (self != NULL, FALSE);
	screen = _g_object_ref0 (gtk_widget_get_screen ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self)));
	if (GTK_WIDGET_REALIZED ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self))) {
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, gdk_screen_get_monitor_at_window (screen, ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self))->window));
	} else {
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
	}
	result = FALSE;
	_g_object_unref0 (screen);
	return result;
}


static void gnomenu_global_menu_adapter_chainup_key_changed (GnomenuGlobalMenuAdapter* self, GtkWindow* window) {
	GType type;
	GtkWindowClass* window_class;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	type = GTK_TYPE_WINDOW;
	window_class = (GtkWindowClass*) g_type_class_ref (type);
	g_debug ("globalmenuadapter.vala:82: chainup to Gtk.Window keys changed");
	window_class->keys_changed (window);
	_g_type_class_unref0 (window_class);
}


static void _gnomenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self) {
	gnomenu_global_menu_adapter_chainup_key_changed (self, _sender);
}


static void _gnomenu_global_menu_adapter_hierarchy_changed_chain_keys (GnomenuGlobalMenuAdapter* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	GtkWidget* _tmp1_;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self)), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWindow*) toplevel, "keys-changed", (GCallback) _gnomenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed, self, 0);
	}
	if ((_tmp1_ = old_toplevel, GTK_IS_PLUG (_tmp1_) ? ((GtkPlug*) _tmp1_) : NULL) != NULL) {
		guint _tmp3_;
		GtkWidget* _tmp2_;
		g_signal_parse_name ("keys-changed", GTK_TYPE_WINDOW, &_tmp3_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GtkWindow*) (_tmp2_ = old_toplevel, GTK_IS_PLUG (_tmp2_) ? ((GtkPlug*) _tmp2_) : NULL), G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp3_, 0, NULL, (GCallback) _gnomenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed, self);
	}
	_g_object_unref0 (toplevel);
}


GnomenuWindow* gnomenu_global_menu_adapter_get_active_window (GnomenuGlobalMenuAdapter* self) {
	GnomenuWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = gnomenu_monitor_get_active_window (self->priv->active_window_monitor);
	return result;
}


static void _gnomenu_global_menu_adapter_emit_active_window_changed_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self) {
	gnomenu_global_menu_adapter_emit_active_window_changed (self, prev_window);
}


static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self) {
	gnomenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_adapter_item_activated_gnomenu_shell_activate (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_adapter_item_activated (self, item);
}


static void _gnomenu_global_menu_adapter_item_selected_gnomenu_shell_select (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_adapter_item_selected (self, item);
}


static void _gnomenu_global_menu_adapter_item_deselected_gnomenu_shell_deselect (GnomenuGlobalMenuAdapter* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_adapter_item_deselected (self, item);
}


static void __gnomenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_gnomenu_global_menu_adapter_hierarchy_changed (self, previous_toplevel);
}


static void __gnomenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_gnomenu_global_menu_adapter_hierarchy_changed_chain_keys (self, previous_toplevel);
}


static GObject * gnomenu_global_menu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GnomenuGlobalMenuAdapter * self;
	parent_class = G_OBJECT_CLASS (gnomenu_global_menu_adapter_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = GNOMENU_GLOBAL_MENU_ADAPTER (obj);
	{
		GnomenuMnemonicKeys* _tmp0_;
		GnomenuMonitor* _tmp1_;
		self->priv->mnemonic_keys = (_tmp0_ = gnomenu_mnemonic_keys_new ((GnomenuShell*) self), _gnomenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys), _tmp0_);
		self->priv->active_window_monitor = (_tmp1_ = gnomenu_monitor_new (gtk_widget_get_screen ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self))), _g_object_unref0 (self->priv->active_window_monitor), _tmp1_);
		gnomenu_monitor_set_managed_shell (self->priv->active_window_monitor, (GnomenuShell*) self);
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _gnomenu_global_menu_adapter_emit_active_window_changed_gnomenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "shell-rebuilt", (GCallback) _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-lost-focus", (GCallback) _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-received-focus", (GCallback) _gnomenu_global_menu_adapter_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "activate", (GCallback) _gnomenu_global_menu_adapter_item_activated_gnomenu_shell_activate, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "select", (GCallback) _gnomenu_global_menu_adapter_item_selected_gnomenu_shell_select, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "deselect", (GCallback) _gnomenu_global_menu_adapter_item_deselected_gnomenu_shell_deselect, self, 0);
		g_signal_connect_object ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self), "hierarchy-changed", (GCallback) __gnomenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed, self, 0);
		g_signal_connect_object ((GtkWidget*) gnomenu_adapter_get_gtk_shell ((GnomenuAdapter*) self), "hierarchy-changed", (GCallback) __gnomenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed, self, 0);
	}
	return obj;
}


static void gnomenu_global_menu_adapter_class_init (GnomenuGlobalMenuAdapterClass * klass) {
	gnomenu_global_menu_adapter_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuGlobalMenuAdapterPrivate));
	G_OBJECT_CLASS (klass)->get_property = gnomenu_global_menu_adapter_get_property;
	G_OBJECT_CLASS (klass)->constructor = gnomenu_global_menu_adapter_constructor;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_global_menu_adapter_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW, g_param_spec_object ("active-window", "active-window", "active-window", GNOMENU_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("active_window_changed", GNOMENU_TYPE_GLOBAL_MENU_ADAPTER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GNOMENU_TYPE_WINDOW);
}


static void gnomenu_global_menu_adapter_instance_init (GnomenuGlobalMenuAdapter * self) {
	self->priv = GNOMENU_GLOBAL_MENU_ADAPTER_GET_PRIVATE (self);
}


static void gnomenu_global_menu_adapter_finalize (GObject* obj) {
	GnomenuGlobalMenuAdapter * self;
	self = GNOMENU_GLOBAL_MENU_ADAPTER (obj);
	_g_object_unref0 (self->priv->active_window_monitor);
	_gnomenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys);
	G_OBJECT_CLASS (gnomenu_global_menu_adapter_parent_class)->finalize (obj);
}


GType gnomenu_global_menu_adapter_get_type (void) {
	static volatile gsize gnomenu_global_menu_adapter_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_global_menu_adapter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuGlobalMenuAdapterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_global_menu_adapter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuGlobalMenuAdapter), 0, (GInstanceInitFunc) gnomenu_global_menu_adapter_instance_init, NULL };
		GType gnomenu_global_menu_adapter_type_id;
		gnomenu_global_menu_adapter_type_id = g_type_register_static (GNOMENU_TYPE_ADAPTER, "GnomenuGlobalMenuAdapter", &g_define_type_info, 0);
		g_once_init_leave (&gnomenu_global_menu_adapter_type_id__volatile, gnomenu_global_menu_adapter_type_id);
	}
	return gnomenu_global_menu_adapter_type_id__volatile;
}


static void gnomenu_global_menu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuGlobalMenuAdapter * self;
	self = GNOMENU_GLOBAL_MENU_ADAPTER (object);
	switch (property_id) {
		case GNOMENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW:
		g_value_set_object (value, gnomenu_global_menu_adapter_get_active_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




