/* globalmenubar.c generated by valac, the Vala compiler
 * generated from globalmenubar.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define GNOMENU_TYPE_SHELL (gnomenu_shell_get_type ())
#define GNOMENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SHELL, GnomenuShell))
#define GNOMENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SHELL))
#define GNOMENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_SHELL, GnomenuShellIface))

typedef struct _GnomenuShell GnomenuShell;
typedef struct _GnomenuShellIface GnomenuShellIface;

#define GNOMENU_TYPE_ITEM (gnomenu_item_get_type ())
#define GNOMENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ITEM, GnomenuItem))
#define GNOMENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ITEM))
#define GNOMENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_ITEM, GnomenuItemIface))

typedef struct _GnomenuItem GnomenuItem;
typedef struct _GnomenuItemIface GnomenuItemIface;

#define GNOMENU_TYPE_ITEM_TYPE (gnomenu_item_type_get_type ())

#define GNOMENU_TYPE_ITEM_STATE (gnomenu_item_state_get_type ())

#define GNOMENU_TYPE_MENU_BAR (gnomenu_menu_bar_get_type ())
#define GNOMENU_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MENU_BAR, GnomenuMenuBar))
#define GNOMENU_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MENU_BAR, GnomenuMenuBarClass))
#define GNOMENU_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MENU_BAR))
#define GNOMENU_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MENU_BAR))
#define GNOMENU_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MENU_BAR, GnomenuMenuBarClass))

typedef struct _GnomenuMenuBar GnomenuMenuBar;
typedef struct _GnomenuMenuBarClass GnomenuMenuBarClass;
typedef struct _GnomenuMenuBarPrivate GnomenuMenuBarPrivate;

#define GNOMENU_TYPE_GLOBAL_MENU_BAR (gnomenu_global_menu_bar_get_type ())
#define GNOMENU_GLOBAL_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_GLOBAL_MENU_BAR, GnomenuGlobalMenuBar))
#define GNOMENU_GLOBAL_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_GLOBAL_MENU_BAR, GnomenuGlobalMenuBarClass))
#define GNOMENU_IS_GLOBAL_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_GLOBAL_MENU_BAR))
#define GNOMENU_IS_GLOBAL_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_GLOBAL_MENU_BAR))
#define GNOMENU_GLOBAL_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_GLOBAL_MENU_BAR, GnomenuGlobalMenuBarClass))

typedef struct _GnomenuGlobalMenuBar GnomenuGlobalMenuBar;
typedef struct _GnomenuGlobalMenuBarClass GnomenuGlobalMenuBarClass;
typedef struct _GnomenuGlobalMenuBarPrivate GnomenuGlobalMenuBarPrivate;

#define GNOMENU_TYPE_WINDOW (gnomenu_window_get_type ())
#define GNOMENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindow))
#define GNOMENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))
#define GNOMENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_WINDOW))
#define GNOMENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_WINDOW))
#define GNOMENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))

typedef struct _GnomenuWindow GnomenuWindow;
typedef struct _GnomenuWindowClass GnomenuWindowClass;

#define GNOMENU_TYPE_MONITOR (gnomenu_monitor_get_type ())
#define GNOMENU_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitor))
#define GNOMENU_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))
#define GNOMENU_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MONITOR))
#define GNOMENU_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MONITOR))
#define GNOMENU_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))

typedef struct _GnomenuMonitor GnomenuMonitor;
typedef struct _GnomenuMonitorClass GnomenuMonitorClass;

#define GNOMENU_TYPE_MNEMONIC_KEYS (gnomenu_mnemonic_keys_get_type ())
#define GNOMENU_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeys))
#define GNOMENU_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))
#define GNOMENU_IS_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_IS_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MNEMONIC_KEYS))
#define GNOMENU_MNEMONIC_KEYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MNEMONIC_KEYS, GnomenuMnemonicKeysClass))

typedef struct _GnomenuMnemonicKeys GnomenuMnemonicKeys;
typedef struct _GnomenuMnemonicKeysClass GnomenuMnemonicKeysClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gnomenu_mnemonic_keys_unref0(var) ((var == NULL) ? NULL : (var = (gnomenu_mnemonic_keys_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define GNOMENU_TYPE_MENU_ITEM (gnomenu_menu_item_get_type ())
#define GNOMENU_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItem))
#define GNOMENU_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItemClass))
#define GNOMENU_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MENU_ITEM))
#define GNOMENU_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MENU_ITEM))
#define GNOMENU_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MENU_ITEM, GnomenuMenuItemClass))

typedef struct _GnomenuMenuItem GnomenuMenuItem;
typedef struct _GnomenuMenuItemClass GnomenuMenuItemClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))

typedef enum  {
	GNOMENU_ITEM_TYPE_NORMAL = 0,
	GNOMENU_ITEM_TYPE_CHECK = 1,
	GNOMENU_ITEM_TYPE_RADIO = 2,
	GNOMENU_ITEM_TYPE_IMAGE = 3,
	GNOMENU_ITEM_TYPE_SEPARATOR = 4,
	GNOMENU_ITEM_TYPE_ARROW = 5,
	GNOMENU_ITEM_TYPE_ICON = 6
} GnomenuItemType;

typedef enum  {
	GNOMENU_ITEM_STATE_UNTOGGLED = 0,
	GNOMENU_ITEM_STATE_TOGGLED = 1,
	GNOMENU_ITEM_STATE_TRISTATE = 2
} GnomenuItemState;

struct _GnomenuItemIface {
	GTypeInterface parent_iface;
	GnomenuShell* (*get_shell) (GnomenuItem* self);
	GnomenuShell* (*get_sub_shell) (GnomenuItem* self);
	gboolean (*get_has_sub_shell) (GnomenuItem* self);
	void (*set_has_sub_shell) (GnomenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (GnomenuItem* self);
	void (*set_client_side_sub_shell) (GnomenuItem* self, gboolean value);
	const char* (*get_item_id) (GnomenuItem* self);
	void (*set_item_id) (GnomenuItem* self, const char* value);
	GnomenuItemType (*get_item_type) (GnomenuItem* self);
	void (*set_item_type) (GnomenuItem* self, GnomenuItemType value);
	gboolean (*get_item_use_underline) (GnomenuItem* self);
	void (*set_item_use_underline) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (GnomenuItem* self);
	void (*set_item_sensitive) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_visible) (GnomenuItem* self);
	void (*set_item_visible) (GnomenuItem* self, gboolean value);
	GnomenuItemState (*get_item_state) (GnomenuItem* self);
	void (*set_item_state) (GnomenuItem* self, GnomenuItemState value);
	const char* (*get_item_label) (GnomenuItem* self);
	void (*set_item_label) (GnomenuItem* self, const char* value);
	const char* (*get_item_icon) (GnomenuItem* self);
	void (*set_item_icon) (GnomenuItem* self, const char* value);
	const char* (*get_item_accel_text) (GnomenuItem* self);
	void (*set_item_accel_text) (GnomenuItem* self, const char* value);
	const char* (*get_item_font) (GnomenuItem* self);
	void (*set_item_font) (GnomenuItem* self, const char* value);
};

struct _GnomenuShellIface {
	GTypeInterface parent_iface;
	GnomenuItem* (*get_item) (GnomenuShell* self, gint position);
	GnomenuItem* (*get_item_by_id) (GnomenuShell* self, const char* id);
	gint (*get_item_position) (GnomenuShell* self, GnomenuItem* item);
	GnomenuItem* (*get_owner) (GnomenuShell* self);
	gint (*get_length) (GnomenuShell* self);
	void (*set_length) (GnomenuShell* self, gint value);
};

struct _GnomenuMenuBar {
	GtkMenuBar parent_instance;
	GnomenuMenuBarPrivate * priv;
};

struct _GnomenuMenuBarClass {
	GtkMenuBarClass parent_class;
};

struct _GnomenuGlobalMenuBar {
	GnomenuMenuBar parent_instance;
	GnomenuGlobalMenuBarPrivate * priv;
	gboolean _grab_menu_key;
};

struct _GnomenuGlobalMenuBarClass {
	GnomenuMenuBarClass parent_class;
};

struct _GnomenuGlobalMenuBarPrivate {
	GnomenuWindow* _root_window;
	GnomenuMonitor* active_window_monitor;
	GnomenuMnemonicKeys* mnemonic_keys;
	gboolean _grab_keys;
};


static gpointer gnomenu_global_menu_bar_parent_class = NULL;

GType gnomenu_item_type_get_type (void) G_GNUC_CONST;
GType gnomenu_item_state_get_type (void) G_GNUC_CONST;
GType gnomenu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_shell_get_type (void) G_GNUC_CONST;
GType gnomenu_menu_bar_get_type (void) G_GNUC_CONST;
GType gnomenu_global_menu_bar_get_type (void) G_GNUC_CONST;
GType gnomenu_window_get_type (void) G_GNUC_CONST;
GType gnomenu_monitor_get_type (void) G_GNUC_CONST;
gpointer gnomenu_mnemonic_keys_ref (gpointer instance);
void gnomenu_mnemonic_keys_unref (gpointer instance);
GParamSpec* gnomenu_param_spec_mnemonic_keys (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void gnomenu_value_set_mnemonic_keys (GValue* value, gpointer v_object);
void gnomenu_value_take_mnemonic_keys (GValue* value, gpointer v_object);
gpointer gnomenu_value_get_mnemonic_keys (const GValue* value);
GType gnomenu_mnemonic_keys_get_type (void) G_GNUC_CONST;
#define GNOMENU_GLOBAL_MENU_BAR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_GLOBAL_MENU_BAR, GnomenuGlobalMenuBarPrivate))
enum  {
	GNOMENU_GLOBAL_MENU_BAR_DUMMY_PROPERTY,
	GNOMENU_GLOBAL_MENU_BAR_PER_MONITOR_MODE,
	GNOMENU_GLOBAL_MENU_BAR_GRAB_KEYS,
	GNOMENU_GLOBAL_MENU_BAR_GRAB_MENU_KEY,
	GNOMENU_GLOBAL_MENU_BAR_ACTIVE_WINDOW
};
static void gnomenu_global_menu_bar_real_dispose (GObject* base);
static void gnomenu_global_menu_bar_emit_active_window_changed (GnomenuGlobalMenuBar* self, GnomenuWindow* prev_window);
GnomenuWindow* gnomenu_global_menu_bar_get_active_window (GnomenuGlobalMenuBar* self);
void gnomenu_window_emit_menu_event (GnomenuWindow* self, const char* path);
char* gnomenu_item_get_item_path (GnomenuItem* self);
static void gnomenu_global_menu_bar_item_activated (GnomenuGlobalMenuBar* self, GnomenuItem* item);
void gnomenu_window_emit_menu_select (GnomenuWindow* self, const char* path, const char* pos);
static void gnomenu_global_menu_bar_item_selected (GnomenuGlobalMenuBar* self, GnomenuItem* item);
void gnomenu_window_emit_menu_deselect (GnomenuWindow* self, const char* path);
static void gnomenu_global_menu_bar_item_deselected (GnomenuGlobalMenuBar* self, GnomenuItem* item);
gboolean gnomenu_monitor_has_pointer (GnomenuMonitor* self);
static gboolean gnomenu_global_menu_bar_really_should_grab_keys (GnomenuGlobalMenuBar* self);
void gnomenu_mnemonic_keys_ungrab (GnomenuMnemonicKeys* self);
static void gnomenu_global_menu_bar_show_underlines (GnomenuGlobalMenuBar* self);
void gnomenu_mnemonic_keys_grab (GnomenuMnemonicKeys* self, GnomenuWindow* window);
static void gnomenu_global_menu_bar_hide_underlines (GnomenuGlobalMenuBar* self);
static void gnomenu_global_menu_bar_regrab_mnemonic_keys (GnomenuGlobalMenuBar* self);
GType gnomenu_menu_item_get_type (void) G_GNUC_CONST;
void gnomenu_menu_item_set_show_underline (GnomenuMenuItem* self, gboolean value);
void gnomenu_monitor_attach (GnomenuMonitor* self, GdkScreen* gdk_screen);
GnomenuWindow* gnomenu_window_new (GdkWindow* window);
GnomenuWindow* gnomenu_window_construct (GType object_type, GdkWindow* window);
void gnomenu_window_set_key_widget (GnomenuWindow* self, GtkWidget* widget);
static void gnomenu_global_menu_bar_grab_menu_bar_key (GnomenuGlobalMenuBar* self);
static void gnomenu_global_menu_bar_regrab_menu_bar_key (GnomenuGlobalMenuBar* self);
static void _gnomenu_global_menu_bar_regrab_menu_bar_key_g_object_notify (GtkSettings* _sender, GParamSpec* pspec, gpointer self);
static void gnomenu_global_menu_bar_attach_to_screen (GnomenuGlobalMenuBar* self, GdkScreen* screen);
static void gnomenu_global_menu_bar_ungrab_menu_bar_key (GnomenuGlobalMenuBar* self);
static void gnomenu_global_menu_bar_detach_from_screen (GnomenuGlobalMenuBar* self, GdkScreen* screen);
void gnomenu_monitor_set_monitor_num (GnomenuMonitor* self, gint value);
static gboolean gnomenu_global_menu_bar_sync_monitor_num (GnomenuGlobalMenuBar* self);
static gboolean _gnomenu_global_menu_bar_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self);
static void _gnomenu_global_menu_bar_hierarchy_changed (GnomenuGlobalMenuBar* self, GtkWidget* old_toplevel);
static void gnomenu_global_menu_bar_chainup_key_changed (GnomenuGlobalMenuBar* self, GtkWindow* window);
static void _gnomenu_global_menu_bar_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self);
static void _gnomenu_global_menu_bar_hierarchy_changed_chain_keys (GnomenuGlobalMenuBar* self, GtkWidget* old_toplevel);
static void _gnomenu_global_menu_bar_screen_changed (GnomenuGlobalMenuBar* self, GdkScreen* previous_screen);
gboolean gnomenu_window_ungrab_key (GnomenuWindow* self, guint keyval, GdkModifierType state);
static void gnomenu_global_menu_bar_get_accel_key (GnomenuGlobalMenuBar* self, guint* keyval, GdkModifierType* mods);
gboolean gnomenu_window_grab_key (GnomenuWindow* self, guint keyval, GdkModifierType state);
GnomenuGlobalMenuBar* gnomenu_global_menu_bar_new (void);
GnomenuGlobalMenuBar* gnomenu_global_menu_bar_construct (GType object_type);
gboolean gnomenu_monitor_get_per_monitor_mode (GnomenuMonitor* self);
gboolean gnomenu_global_menu_bar_get_per_monitor_mode (GnomenuGlobalMenuBar* self);
void gnomenu_monitor_set_per_monitor_mode (GnomenuMonitor* self, gboolean value);
void gnomenu_global_menu_bar_set_per_monitor_mode (GnomenuGlobalMenuBar* self, gboolean value);
gboolean gnomenu_global_menu_bar_get_grab_keys (GnomenuGlobalMenuBar* self);
void gnomenu_global_menu_bar_set_grab_keys (GnomenuGlobalMenuBar* self, gboolean value);
gboolean gnomenu_global_menu_bar_get_grab_menu_key (GnomenuGlobalMenuBar* self);
void gnomenu_global_menu_bar_set_grab_menu_key (GnomenuGlobalMenuBar* self, gboolean value);
GnomenuWindow* gnomenu_monitor_get_active_window (GnomenuMonitor* self);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_new (GnomenuShell* shell);
GnomenuMnemonicKeys* gnomenu_mnemonic_keys_construct (GType object_type, GnomenuShell* shell);
GnomenuMonitor* gnomenu_monitor_new (GdkScreen* screen);
GnomenuMonitor* gnomenu_monitor_construct (GType object_type, GdkScreen* screen);
void gnomenu_monitor_set_managed_shell (GnomenuMonitor* self, GnomenuShell* value);
static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self);
static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus (GnomenuMonitor* _sender, gpointer self);
static void _gnomenu_global_menu_bar_emit_active_window_changed_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self);
static void _gnomenu_global_menu_bar_item_activated_gnomenu_shell_activate (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self);
static void _gnomenu_global_menu_bar_item_selected_gnomenu_shell_select (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self);
static void _gnomenu_global_menu_bar_item_deselected_gnomenu_shell_deselect (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self);
static void __gnomenu_global_menu_bar_screen_changed_gtk_widget_screen_changed (GnomenuGlobalMenuBar* _sender, GdkScreen* previous_screen, gpointer self);
static void __gnomenu_global_menu_bar_hierarchy_changed_gtk_widget_hierarchy_changed (GnomenuGlobalMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self);
static void __gnomenu_global_menu_bar_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GnomenuGlobalMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self);
static void _lambda1_ (GnomenuGlobalMenuBar* self);
static void __lambda1__g_object_notify (GnomenuGlobalMenuBar* _sender, GParamSpec* pspec, gpointer self);
static GObject * gnomenu_global_menu_bar_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void gnomenu_global_menu_bar_finalize (GObject* obj);
static void gnomenu_global_menu_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void gnomenu_global_menu_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static void gnomenu_global_menu_bar_real_dispose (GObject* base) {
	GnomenuGlobalMenuBar * self;
	GnomenuMonitor* _tmp0_;
	GnomenuMnemonicKeys* _tmp1_;
	self = (GnomenuGlobalMenuBar*) base;
	self->priv->active_window_monitor = (_tmp0_ = NULL, _g_object_unref0 (self->priv->active_window_monitor), _tmp0_);
	self->priv->mnemonic_keys = (_tmp1_ = NULL, _gnomenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys), _tmp1_);
	G_OBJECT_CLASS (gnomenu_global_menu_bar_parent_class)->dispose ((GObject*) GNOMENU_MENU_BAR (self));
}


static void gnomenu_global_menu_bar_emit_active_window_changed (GnomenuGlobalMenuBar* self, GnomenuWindow* prev_window) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "active-window-changed", prev_window);
}


static void gnomenu_global_menu_bar_item_activated (GnomenuGlobalMenuBar* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_bar_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_event (gnomenu_global_menu_bar_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static void gnomenu_global_menu_bar_item_selected (GnomenuGlobalMenuBar* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_bar_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_select (gnomenu_global_menu_bar_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item), NULL);
		_g_free0 (_tmp0_);
	}
}


static void gnomenu_global_menu_bar_item_deselected (GnomenuGlobalMenuBar* self, GnomenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (gnomenu_global_menu_bar_get_active_window (self) != NULL) {
		char* _tmp0_;
		gnomenu_window_emit_menu_deselect (gnomenu_global_menu_bar_get_active_window (self), _tmp0_ = gnomenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static gboolean gnomenu_global_menu_bar_really_should_grab_keys (GnomenuGlobalMenuBar* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	if (self->priv->_grab_keys) {
		_tmp0_ = gnomenu_monitor_has_pointer (self->priv->active_window_monitor);
	} else {
		_tmp0_ = FALSE;
	}
	result = _tmp0_;
	return result;
}


static void gnomenu_global_menu_bar_regrab_mnemonic_keys (GnomenuGlobalMenuBar* self) {
	g_return_if_fail (self != NULL);
	gnomenu_mnemonic_keys_ungrab (self->priv->mnemonic_keys);
	if (gnomenu_global_menu_bar_really_should_grab_keys (self)) {
		gnomenu_global_menu_bar_show_underlines (self);
		gnomenu_mnemonic_keys_grab (self->priv->mnemonic_keys, gnomenu_global_menu_bar_get_active_window (self));
	} else {
		gnomenu_global_menu_bar_hide_underlines (self);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void gnomenu_global_menu_bar_show_underlines (GnomenuGlobalMenuBar* self) {
	g_return_if_fail (self != NULL);
	{
		GList* widget_collection;
		GList* widget_it;
		widget_collection = gtk_container_get_children ((GtkContainer*) self);
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
			GtkWidget* widget;
			widget = (GtkWidget*) widget_it->data;
			{
				if (GNOMENU_IS_MENU_ITEM (widget)) {
					GtkWidget* _tmp0_;
					GnomenuMenuItem* item;
					item = _g_object_ref0 ((_tmp0_ = widget, GNOMENU_IS_MENU_ITEM (_tmp0_) ? ((GnomenuMenuItem*) _tmp0_) : NULL));
					gnomenu_menu_item_set_show_underline (item, TRUE);
					_g_object_unref0 (item);
				}
			}
		}
		_g_list_free0 (widget_collection);
	}
}


static void gnomenu_global_menu_bar_hide_underlines (GnomenuGlobalMenuBar* self) {
	g_return_if_fail (self != NULL);
	{
		GList* widget_collection;
		GList* widget_it;
		widget_collection = gtk_container_get_children ((GtkContainer*) self);
		for (widget_it = widget_collection; widget_it != NULL; widget_it = widget_it->next) {
			GtkWidget* widget;
			widget = (GtkWidget*) widget_it->data;
			{
				if (GNOMENU_IS_MENU_ITEM (widget)) {
					GtkWidget* _tmp0_;
					GnomenuMenuItem* item;
					item = _g_object_ref0 ((_tmp0_ = widget, GNOMENU_IS_MENU_ITEM (_tmp0_) ? ((GnomenuMenuItem*) _tmp0_) : NULL));
					gnomenu_menu_item_set_show_underline (item, FALSE);
					_g_object_unref0 (item);
				}
			}
		}
		_g_list_free0 (widget_collection);
	}
}


static void _gnomenu_global_menu_bar_regrab_menu_bar_key_g_object_notify (GtkSettings* _sender, GParamSpec* pspec, gpointer self) {
	gnomenu_global_menu_bar_regrab_menu_bar_key (self);
}


static void gnomenu_global_menu_bar_attach_to_screen (GnomenuGlobalMenuBar* self, GdkScreen* screen) {
	GnomenuWindow* _tmp0_;
	GtkSettings* settings;
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	gnomenu_monitor_attach (self->priv->active_window_monitor, screen);
	self->priv->_root_window = (_tmp0_ = gnomenu_window_new (gtk_widget_get_root_window ((GtkWidget*) self)), _g_object_unref0 (self->priv->_root_window), _tmp0_);
	gnomenu_window_set_key_widget (self->priv->_root_window, gtk_widget_get_toplevel ((GtkWidget*) self));
	gnomenu_global_menu_bar_grab_menu_bar_key (self);
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
	settings = _g_object_ref0 (gtk_widget_get_settings ((GtkWidget*) self));
	g_signal_connect_object ((GObject*) settings, "notify::gtk-menu-bar-accel", (GCallback) _gnomenu_global_menu_bar_regrab_menu_bar_key_g_object_notify, self, 0);
	_g_object_unref0 (settings);
}


static void gnomenu_global_menu_bar_detach_from_screen (GnomenuGlobalMenuBar* self, GdkScreen* screen) {
	GtkSettings* settings;
	GQuark _tmp1_;
	guint _tmp0_;
	GnomenuWindow* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	if (self->priv->_root_window != NULL) {
		gnomenu_window_set_key_widget (self->priv->_root_window, NULL);
		gnomenu_global_menu_bar_ungrab_menu_bar_key (self);
		gnomenu_mnemonic_keys_ungrab (self->priv->mnemonic_keys);
	}
	settings = _g_object_ref0 (gtk_widget_get_settings ((GtkWidget*) self));
	g_signal_parse_name ("notify::gtk-menu-bar-accel", G_TYPE_OBJECT, &_tmp0_, &_tmp1_, TRUE);
	g_signal_handlers_disconnect_matched ((GObject*) settings, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_DETAIL | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, _tmp1_, NULL, (GCallback) _gnomenu_global_menu_bar_regrab_menu_bar_key_g_object_notify, self);
	self->priv->_root_window = (_tmp2_ = NULL, _g_object_unref0 (self->priv->_root_window), _tmp2_);
	_g_object_unref0 (settings);
}


static gboolean gnomenu_global_menu_bar_sync_monitor_num (GnomenuGlobalMenuBar* self) {
	gboolean result = FALSE;
	GdkScreen* screen;
	g_return_val_if_fail (self != NULL, FALSE);
	screen = _g_object_ref0 (gtk_widget_get_screen ((GtkWidget*) self));
	if (GTK_WIDGET_REALIZED ((GtkWidget*) self)) {
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, gdk_screen_get_monitor_at_window (screen, ((GtkWidget*) self)->window));
	} else {
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
	}
	result = FALSE;
	_g_object_unref0 (screen);
	return result;
}


static gboolean _gnomenu_global_menu_bar_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self) {
	gboolean result;
	result = gnomenu_global_menu_bar_sync_monitor_num (self);
	return result;
}


static void _gnomenu_global_menu_bar_hierarchy_changed (GnomenuGlobalMenuBar* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWidget*) toplevel, "configure-event", (GCallback) _gnomenu_global_menu_bar_sync_monitor_num_gtk_widget_configure_event, self, 0);
	}
	if (old_toplevel != NULL) {
		guint _tmp1_;
		g_signal_parse_name ("configure-event", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (old_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _gnomenu_global_menu_bar_sync_monitor_num_gtk_widget_configure_event, self);
	}
	_g_object_unref0 (toplevel);
}


static void gnomenu_global_menu_bar_chainup_key_changed (GnomenuGlobalMenuBar* self, GtkWindow* window) {
	GType type;
	GtkWindowClass* window_class;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	type = GTK_TYPE_WINDOW;
	window_class = (GtkWindowClass*) g_type_class_ref (type);
	g_debug ("globalmenubar.vala:165: chainup to Gtk.Window keys changed");
	window_class->keys_changed (window);
	_g_type_class_unref0 (window_class);
}


static void _gnomenu_global_menu_bar_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self) {
	gnomenu_global_menu_bar_chainup_key_changed (self, _sender);
}


static void _gnomenu_global_menu_bar_hierarchy_changed_chain_keys (GnomenuGlobalMenuBar* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	GtkWidget* _tmp1_;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWindow*) toplevel, "keys-changed", (GCallback) _gnomenu_global_menu_bar_chainup_key_changed_gtk_window_keys_changed, self, 0);
	}
	if ((_tmp1_ = old_toplevel, GTK_IS_PLUG (_tmp1_) ? ((GtkPlug*) _tmp1_) : NULL) != NULL) {
		guint _tmp3_;
		GtkWidget* _tmp2_;
		g_signal_parse_name ("keys-changed", GTK_TYPE_WINDOW, &_tmp3_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GtkWindow*) (_tmp2_ = old_toplevel, GTK_IS_PLUG (_tmp2_) ? ((GtkPlug*) _tmp2_) : NULL), G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp3_, 0, NULL, (GCallback) _gnomenu_global_menu_bar_chainup_key_changed_gtk_window_keys_changed, self);
	}
	_g_object_unref0 (toplevel);
}


static void _gnomenu_global_menu_bar_screen_changed (GnomenuGlobalMenuBar* self, GdkScreen* previous_screen) {
	GdkScreen* screen;
	g_return_if_fail (self != NULL);
	screen = _g_object_ref0 (gtk_widget_get_screen ((GtkWidget*) self));
	if (previous_screen != screen) {
		if (previous_screen != NULL) {
			gnomenu_global_menu_bar_detach_from_screen (self, previous_screen);
		}
		if (screen != NULL) {
			gnomenu_global_menu_bar_attach_to_screen (self, screen);
		}
	}
	_g_object_unref0 (screen);
}


static void gnomenu_global_menu_bar_regrab_menu_bar_key (GnomenuGlobalMenuBar* self) {
	g_return_if_fail (self != NULL);
	g_debug ("globalmenubar.vala:191: regrab menu_bar key");
	gnomenu_global_menu_bar_ungrab_menu_bar_key (self);
	gnomenu_global_menu_bar_grab_menu_bar_key (self);
}


static void gnomenu_global_menu_bar_ungrab_menu_bar_key (GnomenuGlobalMenuBar* self) {
	gint keyval;
	GdkModifierType mods;
	g_return_if_fail (self != NULL);
	keyval = GPOINTER_TO_INT (g_object_get_data ((GObject*) self->priv->_root_window, "menu-bar-keyval"));
	mods = (GdkModifierType) GPOINTER_TO_INT (g_object_get_data ((GObject*) self->priv->_root_window, "menu-bar-keymods"));
	gnomenu_window_ungrab_key (self->priv->_root_window, (guint) keyval, mods);
	g_object_set_data_full ((GObject*) self->priv->_root_window, "menu-bar-keyval", NULL, NULL);
	g_object_set_data_full ((GObject*) self->priv->_root_window, "menu-bar-keymods", NULL, NULL);
}


static void gnomenu_global_menu_bar_grab_menu_bar_key (GnomenuGlobalMenuBar* self) {
	guint keyval = 0U;
	GdkModifierType mods = 0;
	g_return_if_fail (self != NULL);
	gnomenu_global_menu_bar_get_accel_key (self, &keyval, &mods);
	if (self->_grab_menu_key) {
		gnomenu_window_grab_key (self->priv->_root_window, keyval, mods);
	}
	g_object_set_data_full ((GObject*) self->priv->_root_window, "menu-bar-keyval", (void*) keyval, NULL);
	g_object_set_data_full ((GObject*) self->priv->_root_window, "menu-bar-keymods", (void*) mods, NULL);
}


static void gnomenu_global_menu_bar_get_accel_key (GnomenuGlobalMenuBar* self, guint* keyval, GdkModifierType* mods) {
	GtkSettings* settings;
	char* accel;
	g_return_if_fail (self != NULL);
	settings = _g_object_ref0 (gtk_widget_get_settings ((GtkWidget*) self));
	accel = NULL;
	g_object_get ((GObject*) settings, "gtk_menu_bar_accel", &accel, NULL, NULL);
	if (accel != NULL) {
		gtk_accelerator_parse (accel, keyval, mods);
	}
	_g_free0 (accel);
	_g_object_unref0 (settings);
}


GnomenuGlobalMenuBar* gnomenu_global_menu_bar_construct (GType object_type) {
	GnomenuGlobalMenuBar * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


GnomenuGlobalMenuBar* gnomenu_global_menu_bar_new (void) {
	return gnomenu_global_menu_bar_construct (GNOMENU_TYPE_GLOBAL_MENU_BAR);
}


gboolean gnomenu_global_menu_bar_get_per_monitor_mode (GnomenuGlobalMenuBar* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = gnomenu_monitor_get_per_monitor_mode (self->priv->active_window_monitor);
	return result;
}


void gnomenu_global_menu_bar_set_per_monitor_mode (GnomenuGlobalMenuBar* self, gboolean value) {
	g_return_if_fail (self != NULL);
	gnomenu_monitor_set_per_monitor_mode (self->priv->active_window_monitor, value);
	g_object_notify ((GObject *) self, "per-monitor-mode");
}


gboolean gnomenu_global_menu_bar_get_grab_keys (GnomenuGlobalMenuBar* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_grab_keys;
	return result;
}


void gnomenu_global_menu_bar_set_grab_keys (GnomenuGlobalMenuBar* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_grab_keys = value;
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
	g_object_notify ((GObject *) self, "grab-keys");
}


gboolean gnomenu_global_menu_bar_get_grab_menu_key (GnomenuGlobalMenuBar* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->_grab_menu_key;
	return result;
}


void gnomenu_global_menu_bar_set_grab_menu_key (GnomenuGlobalMenuBar* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->_grab_menu_key = value;
	gnomenu_global_menu_bar_regrab_menu_bar_key (self);
	g_object_notify ((GObject *) self, "grab-menu-key");
}


GnomenuWindow* gnomenu_global_menu_bar_get_active_window (GnomenuGlobalMenuBar* self) {
	GnomenuWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = gnomenu_monitor_get_active_window (self->priv->active_window_monitor);
	return result;
}


static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self) {
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus (GnomenuMonitor* _sender, gpointer self) {
	gnomenu_global_menu_bar_regrab_mnemonic_keys (self);
}


static void _gnomenu_global_menu_bar_emit_active_window_changed_gnomenu_monitor_active_window_changed (GnomenuMonitor* _sender, GnomenuWindow* prev_window, gpointer self) {
	gnomenu_global_menu_bar_emit_active_window_changed (self, prev_window);
}


static void _gnomenu_global_menu_bar_item_activated_gnomenu_shell_activate (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_bar_item_activated (self, item);
}


static void _gnomenu_global_menu_bar_item_selected_gnomenu_shell_select (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_bar_item_selected (self, item);
}


static void _gnomenu_global_menu_bar_item_deselected_gnomenu_shell_deselect (GnomenuGlobalMenuBar* _sender, GnomenuItem* item, gpointer self) {
	gnomenu_global_menu_bar_item_deselected (self, item);
}


static void __gnomenu_global_menu_bar_screen_changed_gtk_widget_screen_changed (GnomenuGlobalMenuBar* _sender, GdkScreen* previous_screen, gpointer self) {
	_gnomenu_global_menu_bar_screen_changed (self, previous_screen);
}


static void __gnomenu_global_menu_bar_hierarchy_changed_gtk_widget_hierarchy_changed (GnomenuGlobalMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_gnomenu_global_menu_bar_hierarchy_changed (self, previous_toplevel);
}


static void __gnomenu_global_menu_bar_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GnomenuGlobalMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_gnomenu_global_menu_bar_hierarchy_changed_chain_keys (self, previous_toplevel);
}


static void _lambda1_ (GnomenuGlobalMenuBar* self) {
	if (gtk_widget_get_visible ((GtkWidget*) self) == FALSE) {
		gnomenu_monitor_set_managed_shell (self->priv->active_window_monitor, NULL);
	} else {
		gnomenu_monitor_set_managed_shell (self->priv->active_window_monitor, (GnomenuShell*) self);
	}
}


static void __lambda1__g_object_notify (GnomenuGlobalMenuBar* _sender, GParamSpec* pspec, gpointer self) {
	_lambda1_ (self);
}


static GObject * gnomenu_global_menu_bar_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GnomenuGlobalMenuBar * self;
	parent_class = G_OBJECT_CLASS (gnomenu_global_menu_bar_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = GNOMENU_GLOBAL_MENU_BAR (obj);
	{
		GnomenuMnemonicKeys* _tmp0_;
		GnomenuMonitor* _tmp1_;
		self->priv->mnemonic_keys = (_tmp0_ = gnomenu_mnemonic_keys_new ((GnomenuShell*) self), _gnomenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys), _tmp0_);
		self->priv->active_window_monitor = (_tmp1_ = gnomenu_monitor_new (gtk_widget_get_screen ((GtkWidget*) self)), _g_object_unref0 (self->priv->active_window_monitor), _tmp1_);
		gnomenu_monitor_set_managed_shell (self->priv->active_window_monitor, (GnomenuShell*) self);
		gnomenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "shell-rebuilt", (GCallback) _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_shell_rebuilt, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-lost-focus", (GCallback) _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_lost_focus, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-received-focus", (GCallback) _gnomenu_global_menu_bar_regrab_mnemonic_keys_gnomenu_monitor_active_window_received_focus, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _gnomenu_global_menu_bar_emit_active_window_changed_gnomenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "activate", (GCallback) _gnomenu_global_menu_bar_item_activated_gnomenu_shell_activate, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "select", (GCallback) _gnomenu_global_menu_bar_item_selected_gnomenu_shell_select, self, 0);
		g_signal_connect_object ((GnomenuShell*) self, "deselect", (GCallback) _gnomenu_global_menu_bar_item_deselected_gnomenu_shell_deselect, self, 0);
		g_signal_connect_object ((GtkWidget*) self, "screen-changed", (GCallback) __gnomenu_global_menu_bar_screen_changed_gtk_widget_screen_changed, self, 0);
		g_signal_connect_object ((GtkWidget*) self, "hierarchy-changed", (GCallback) __gnomenu_global_menu_bar_hierarchy_changed_gtk_widget_hierarchy_changed, self, 0);
		g_signal_connect_object ((GtkWidget*) self, "hierarchy-changed", (GCallback) __gnomenu_global_menu_bar_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed, self, 0);
		g_signal_connect_object ((GObject*) self, "notify::visible", (GCallback) __lambda1__g_object_notify, self, 0);
	}
	return obj;
}


static void gnomenu_global_menu_bar_class_init (GnomenuGlobalMenuBarClass * klass) {
	gnomenu_global_menu_bar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuGlobalMenuBarPrivate));
	G_OBJECT_CLASS (klass)->dispose = gnomenu_global_menu_bar_real_dispose;
	G_OBJECT_CLASS (klass)->get_property = gnomenu_global_menu_bar_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomenu_global_menu_bar_set_property;
	G_OBJECT_CLASS (klass)->constructor = gnomenu_global_menu_bar_constructor;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_global_menu_bar_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_MENU_BAR_PER_MONITOR_MODE, g_param_spec_boolean ("per-monitor-mode", "per-monitor-mode", "per-monitor-mode", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_MENU_BAR_GRAB_KEYS, g_param_spec_boolean ("grab-keys", "grab-keys", "grab-keys", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_MENU_BAR_GRAB_MENU_KEY, g_param_spec_boolean ("grab-menu-key", "grab-menu-key", "grab-menu-key", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_GLOBAL_MENU_BAR_ACTIVE_WINDOW, g_param_spec_object ("active-window", "active-window", "active-window", GNOMENU_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("active_window_changed", GNOMENU_TYPE_GLOBAL_MENU_BAR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GNOMENU_TYPE_WINDOW);
}


static void gnomenu_global_menu_bar_instance_init (GnomenuGlobalMenuBar * self) {
	self->priv = GNOMENU_GLOBAL_MENU_BAR_GET_PRIVATE (self);
	self->priv->_grab_keys = TRUE;
	self->_grab_menu_key = TRUE;
}


static void gnomenu_global_menu_bar_finalize (GObject* obj) {
	GnomenuGlobalMenuBar * self;
	self = GNOMENU_GLOBAL_MENU_BAR (obj);
	_g_object_unref0 (self->priv->_root_window);
	_g_object_unref0 (self->priv->active_window_monitor);
	_gnomenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys);
	G_OBJECT_CLASS (gnomenu_global_menu_bar_parent_class)->finalize (obj);
}


GType gnomenu_global_menu_bar_get_type (void) {
	static volatile gsize gnomenu_global_menu_bar_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_global_menu_bar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuGlobalMenuBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_global_menu_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuGlobalMenuBar), 0, (GInstanceInitFunc) gnomenu_global_menu_bar_instance_init, NULL };
		GType gnomenu_global_menu_bar_type_id;
		gnomenu_global_menu_bar_type_id = g_type_register_static (GNOMENU_TYPE_MENU_BAR, "GnomenuGlobalMenuBar", &g_define_type_info, 0);
		g_once_init_leave (&gnomenu_global_menu_bar_type_id__volatile, gnomenu_global_menu_bar_type_id);
	}
	return gnomenu_global_menu_bar_type_id__volatile;
}


static void gnomenu_global_menu_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuGlobalMenuBar * self;
	self = GNOMENU_GLOBAL_MENU_BAR (object);
	switch (property_id) {
		case GNOMENU_GLOBAL_MENU_BAR_PER_MONITOR_MODE:
		g_value_set_boolean (value, gnomenu_global_menu_bar_get_per_monitor_mode (self));
		break;
		case GNOMENU_GLOBAL_MENU_BAR_GRAB_KEYS:
		g_value_set_boolean (value, gnomenu_global_menu_bar_get_grab_keys (self));
		break;
		case GNOMENU_GLOBAL_MENU_BAR_GRAB_MENU_KEY:
		g_value_set_boolean (value, gnomenu_global_menu_bar_get_grab_menu_key (self));
		break;
		case GNOMENU_GLOBAL_MENU_BAR_ACTIVE_WINDOW:
		g_value_set_object (value, gnomenu_global_menu_bar_get_active_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomenu_global_menu_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GnomenuGlobalMenuBar * self;
	self = GNOMENU_GLOBAL_MENU_BAR (object);
	switch (property_id) {
		case GNOMENU_GLOBAL_MENU_BAR_PER_MONITOR_MODE:
		gnomenu_global_menu_bar_set_per_monitor_mode (self, g_value_get_boolean (value));
		break;
		case GNOMENU_GLOBAL_MENU_BAR_GRAB_KEYS:
		gnomenu_global_menu_bar_set_grab_keys (self, g_value_get_boolean (value));
		break;
		case GNOMENU_GLOBAL_MENU_BAR_GRAB_MENU_KEY:
		gnomenu_global_menu_bar_set_grab_menu_key (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




