/* monitor.c generated by valac, the Vala compiler
 * generated from monitor.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libwnck/libwnck.h>
#include <gdk/gdk.h>


#define GNOMENU_TYPE_MONITOR (gnomenu_monitor_get_type ())
#define GNOMENU_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitor))
#define GNOMENU_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))
#define GNOMENU_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_MONITOR))
#define GNOMENU_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_MONITOR))
#define GNOMENU_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_MONITOR, GnomenuMonitorClass))

typedef struct _GnomenuMonitor GnomenuMonitor;
typedef struct _GnomenuMonitorClass GnomenuMonitorClass;
typedef struct _GnomenuMonitorPrivate GnomenuMonitorPrivate;

#define GNOMENU_TYPE_SHELL (gnomenu_shell_get_type ())
#define GNOMENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_SHELL, GnomenuShell))
#define GNOMENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_SHELL))
#define GNOMENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_SHELL, GnomenuShellIface))

typedef struct _GnomenuShell GnomenuShell;
typedef struct _GnomenuShellIface GnomenuShellIface;

#define GNOMENU_TYPE_ITEM (gnomenu_item_get_type ())
#define GNOMENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_ITEM, GnomenuItem))
#define GNOMENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_ITEM))
#define GNOMENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), GNOMENU_TYPE_ITEM, GnomenuItemIface))

typedef struct _GnomenuItem GnomenuItem;
typedef struct _GnomenuItemIface GnomenuItemIface;

#define GNOMENU_TYPE_ITEM_TYPE (gnomenu_item_type_get_type ())

#define GNOMENU_TYPE_ITEM_STATE (gnomenu_item_state_get_type ())

#define GNOMENU_TYPE_WINDOW (gnomenu_window_get_type ())
#define GNOMENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindow))
#define GNOMENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))
#define GNOMENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNOMENU_TYPE_WINDOW))
#define GNOMENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNOMENU_TYPE_WINDOW))
#define GNOMENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNOMENU_TYPE_WINDOW, GnomenuWindowClass))

typedef struct _GnomenuWindow GnomenuWindow;
typedef struct _GnomenuWindowClass GnomenuWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _GnomenuMonitor {
	GObject parent_instance;
	GnomenuMonitorPrivate * priv;
};

struct _GnomenuMonitorClass {
	GObjectClass parent_class;
};

typedef enum  {
	GNOMENU_ITEM_TYPE_NORMAL = 0,
	GNOMENU_ITEM_TYPE_CHECK = 1,
	GNOMENU_ITEM_TYPE_RADIO = 2,
	GNOMENU_ITEM_TYPE_IMAGE = 3,
	GNOMENU_ITEM_TYPE_SEPARATOR = 4,
	GNOMENU_ITEM_TYPE_ARROW = 5,
	GNOMENU_ITEM_TYPE_ICON = 6
} GnomenuItemType;

typedef enum  {
	GNOMENU_ITEM_STATE_UNTOGGLED = 0,
	GNOMENU_ITEM_STATE_TOGGLED = 1,
	GNOMENU_ITEM_STATE_TRISTATE = 2
} GnomenuItemState;

struct _GnomenuItemIface {
	GTypeInterface parent_iface;
	GnomenuShell* (*get_shell) (GnomenuItem* self);
	GnomenuShell* (*get_sub_shell) (GnomenuItem* self);
	gboolean (*get_has_sub_shell) (GnomenuItem* self);
	void (*set_has_sub_shell) (GnomenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (GnomenuItem* self);
	void (*set_client_side_sub_shell) (GnomenuItem* self, gboolean value);
	const char* (*get_item_id) (GnomenuItem* self);
	void (*set_item_id) (GnomenuItem* self, const char* value);
	GnomenuItemType (*get_item_type) (GnomenuItem* self);
	void (*set_item_type) (GnomenuItem* self, GnomenuItemType value);
	gboolean (*get_item_use_underline) (GnomenuItem* self);
	void (*set_item_use_underline) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (GnomenuItem* self);
	void (*set_item_sensitive) (GnomenuItem* self, gboolean value);
	gboolean (*get_item_visible) (GnomenuItem* self);
	void (*set_item_visible) (GnomenuItem* self, gboolean value);
	GnomenuItemState (*get_item_state) (GnomenuItem* self);
	void (*set_item_state) (GnomenuItem* self, GnomenuItemState value);
	const char* (*get_item_label) (GnomenuItem* self);
	void (*set_item_label) (GnomenuItem* self, const char* value);
	const char* (*get_item_icon) (GnomenuItem* self);
	void (*set_item_icon) (GnomenuItem* self, const char* value);
	const char* (*get_item_accel_text) (GnomenuItem* self);
	void (*set_item_accel_text) (GnomenuItem* self, const char* value);
	const char* (*get_item_font) (GnomenuItem* self);
	void (*set_item_font) (GnomenuItem* self, const char* value);
};

struct _GnomenuShellIface {
	GTypeInterface parent_iface;
	GnomenuItem* (*get_item) (GnomenuShell* self, gint position);
	GnomenuItem* (*get_item_by_id) (GnomenuShell* self, const char* id);
	gint (*get_item_position) (GnomenuShell* self, GnomenuItem* item);
	GnomenuItem* (*get_owner) (GnomenuShell* self);
	gint (*get_length) (GnomenuShell* self);
	void (*set_length) (GnomenuShell* self, gint value);
};

struct _GnomenuMonitorPrivate {
	GnomenuShell* _managed_shell;
	gint _monitor_num;
	gboolean _per_monitor_mode;
	GnomenuWindow* _active_window;
	GnomenuWindow* _dummy_window;
	GnomenuWindow* _desktop_window;
	WnckScreen* _screen;
	WnckWindow* _wnck_desktop_window;
	WnckWindow* _wnck_active_window;
	WnckWindow* _wnck_dummy_window;
	gboolean disposed;
	gboolean _wnck_active_window_is_closed;
};


static gpointer gnomenu_monitor_parent_class = NULL;

GType gnomenu_monitor_get_type (void) G_GNUC_CONST;
GType gnomenu_item_type_get_type (void) G_GNUC_CONST;
GType gnomenu_item_state_get_type (void) G_GNUC_CONST;
GType gnomenu_item_get_type (void) G_GNUC_CONST;
GType gnomenu_shell_get_type (void) G_GNUC_CONST;
GType gnomenu_window_get_type (void) G_GNUC_CONST;
#define GNOMENU_MONITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNOMENU_TYPE_MONITOR, GnomenuMonitorPrivate))
enum  {
	GNOMENU_MONITOR_DUMMY_PROPERTY,
	GNOMENU_MONITOR_MANAGED_SHELL,
	GNOMENU_MONITOR_MONITOR_NUM,
	GNOMENU_MONITOR_PER_MONITOR_MODE,
	GNOMENU_MONITOR_ACTIVE_WINDOW
};
static WnckScreen* gnomenu_monitor_gdk_screen_to_wnck_screen (GdkScreen* screen);
static GdkScreen* gnomenu_monitor_wnck_screen_to_gdk_screen (WnckScreen* screen);
static void gnomenu_monitor_detach_from_screen (GnomenuMonitor* self);
static void gnomenu_monitor_attach_to_screen (GnomenuMonitor* self);
void gnomenu_monitor_attach (GnomenuMonitor* self, GdkScreen* gdk_screen);
static gint gnomenu_monitor_get_monitor_num_at_pointer (GnomenuMonitor* self);
gboolean gnomenu_monitor_has_pointer (GnomenuMonitor* self);
GnomenuMonitor* gnomenu_monitor_new (GdkScreen* screen);
GnomenuMonitor* gnomenu_monitor_construct (GType object_type, GdkScreen* screen);
static void gnomenu_monitor_real_dispose (GObject* base);
static void gnomenu_monitor_update_desktop_window (GnomenuMonitor* self);
static void gnomenu_monitor_wnck_status_changed (GnomenuMonitor* self);
static void gnomenu_monitor_on_window_closed (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* window);
static void gnomenu_monitor_on_window_opened (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* window);
static void gnomenu_monitor_on_active_window_changed (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* previous_window);
GnomenuWindow* gnomenu_window_foreign_new (gulong xid);
gboolean gnomenu_monitor_get_per_monitor_mode (GnomenuMonitor* self);
gint gnomenu_window_get_monitor_num (GnomenuWindow* self);
static gboolean gnomenu_monitor_is_window_on_my_monitor (GnomenuMonitor* self, GnomenuWindow* win);
static void gnomenu_monitor_update_active_window (GnomenuMonitor* self, WnckWindow* from_wnck_window);
gboolean gnomenu_window_is_on_active_workspace (GnomenuWindow* self);
static void gnomenu_monitor_replace_active_window (GnomenuMonitor* self, GnomenuWindow* new);
static void gnomenu_monitor_replace_dummy_window (GnomenuMonitor* self, GnomenuWindow* new);
static void gnomenu_monitor_rebuild_managed_shell (GnomenuMonitor* self);
static void _gnomenu_monitor_rebuild_managed_shell_gnomenu_window_menu_context_changed (GnomenuWindow* _sender, gpointer self);
static void gnomenu_monitor_active_window_moved (GnomenuMonitor* self);
static void _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed (GnomenuWindow* _sender, gint prev_num, gpointer self);
WnckWindow* gnomenu_window_get_wnck_window (GnomenuWindow* self);
void gnomenu_shell_set_length (GnomenuShell* self, gint value);
char* gnomenu_window_get_menu_context (GnomenuWindow* self);
void gnomenu_parser_parse (GnomenuShell* shell, const char* description, GError** error);
void gnomenu_monitor_rebuild_shell (GnomenuMonitor* self, GnomenuShell* shell);
static void _gnomenu_monitor_on_window_opened_wnck_screen_window_opened (WnckScreen* _sender, WnckWindow* window, gpointer self);
static void _gnomenu_monitor_on_window_closed_wnck_screen_window_closed (WnckScreen* _sender, WnckWindow* window, gpointer self);
static void _gnomenu_monitor_on_active_window_changed_wnck_screen_active_window_changed (WnckScreen* _sender, WnckWindow* previous_window, gpointer self);
GnomenuShell* gnomenu_monitor_get_managed_shell (GnomenuMonitor* self);
void gnomenu_monitor_set_managed_shell (GnomenuMonitor* self, GnomenuShell* value);
gint gnomenu_monitor_get_monitor_num (GnomenuMonitor* self);
void gnomenu_monitor_set_monitor_num (GnomenuMonitor* self, gint value);
void gnomenu_monitor_set_per_monitor_mode (GnomenuMonitor* self, gboolean value);
GnomenuWindow* gnomenu_monitor_get_active_window (GnomenuMonitor* self);
static void gnomenu_monitor_set_active_window (GnomenuMonitor* self, GnomenuWindow* value);
static void gnomenu_monitor_finalize (GObject* obj);
static void gnomenu_monitor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void gnomenu_monitor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static WnckScreen* gnomenu_monitor_gdk_screen_to_wnck_screen (GdkScreen* screen) {
	WnckScreen* result = NULL;
	if (screen != NULL) {
		result = _g_object_ref0 (wnck_screen_get (gdk_screen_get_number (screen)));
		return result;
	}
	result = NULL;
	return result;
}


static GdkScreen* gnomenu_monitor_wnck_screen_to_gdk_screen (WnckScreen* screen) {
	GdkScreen* result = NULL;
	GdkDisplay* display;
	display = _g_object_ref0 (gdk_display_get_default ());
	if (screen != NULL) {
		result = _g_object_ref0 (gdk_display_get_screen (display, wnck_screen_get_number (screen)));
		_g_object_unref0 (display);
		return result;
	}
	result = NULL;
	_g_object_unref0 (display);
	return result;
}


void gnomenu_monitor_attach (GnomenuMonitor* self, GdkScreen* gdk_screen) {
	WnckScreen* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gdk_screen != NULL);
	gnomenu_monitor_detach_from_screen (self);
	self->priv->_screen = (_tmp0_ = gnomenu_monitor_gdk_screen_to_wnck_screen (gdk_screen), _g_object_unref0 (self->priv->_screen), _tmp0_);
	gnomenu_monitor_attach_to_screen (self);
}


gboolean gnomenu_monitor_has_pointer (GnomenuMonitor* self) {
	gboolean result = FALSE;
	gint num;
	g_return_val_if_fail (self != NULL, FALSE);
	if (self->priv->_monitor_num == (-1)) {
		result = TRUE;
		return result;
	}
	num = gnomenu_monitor_get_monitor_num_at_pointer (self);
	if (self->priv->_monitor_num == num) {
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


GnomenuMonitor* gnomenu_monitor_construct (GType object_type, GdkScreen* screen) {
	GnomenuMonitor * self;
	self = (GnomenuMonitor*) g_object_new (object_type, NULL);
	gnomenu_monitor_attach (self, screen);
	return self;
}


GnomenuMonitor* gnomenu_monitor_new (GdkScreen* screen) {
	return gnomenu_monitor_construct (GNOMENU_TYPE_MONITOR, screen);
}


static void gnomenu_monitor_real_dispose (GObject* base) {
	GnomenuMonitor * self;
	self = (GnomenuMonitor*) base;
	if (!self->priv->disposed) {
		self->priv->disposed = TRUE;
		gnomenu_monitor_detach_from_screen (self);
	}
}


static void gnomenu_monitor_on_window_closed (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* window) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	g_return_if_fail (window != NULL);
	if (self->priv->_wnck_desktop_window == window) {
		gnomenu_monitor_update_desktop_window (self);
	}
	if (window == self->priv->_wnck_active_window) {
		self->priv->_wnck_active_window_is_closed = TRUE;
		gnomenu_monitor_wnck_status_changed (self);
		self->priv->_wnck_active_window_is_closed = FALSE;
	}
}


static void gnomenu_monitor_on_window_opened (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* window) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	g_return_if_fail (window != NULL);
	if (wnck_window_get_window_type (window) == WNCK_WINDOW_DESKTOP) {
		gnomenu_monitor_update_desktop_window (self);
	}
	if (self->priv->_wnck_active_window == NULL) {
		gnomenu_monitor_wnck_status_changed (self);
	}
}


static void gnomenu_monitor_on_active_window_changed (GnomenuMonitor* self, WnckScreen* screen, WnckWindow* previous_window) {
	WnckWindow* window;
	g_return_if_fail (self != NULL);
	g_return_if_fail (screen != NULL);
	window = _g_object_ref0 (wnck_screen_get_active_window (screen));
	if (window == NULL) {
		if (previous_window == NULL) {
			gnomenu_monitor_wnck_status_changed (self);
		}
	} else {
		gnomenu_monitor_wnck_status_changed (self);
	}
	_g_object_unref0 (window);
}


static void gnomenu_monitor_update_desktop_window (GnomenuMonitor* self) {
	GList* windows;
	WnckWindow* _tmp0_;
	g_return_if_fail (self != NULL);
	windows = wnck_screen_get_windows (self->priv->_screen);
	self->priv->_wnck_desktop_window = (_tmp0_ = NULL, _g_object_unref0 (self->priv->_wnck_desktop_window), _tmp0_);
	{
		GList* window_collection;
		GList* window_it;
		window_collection = windows;
		for (window_it = window_collection; window_it != NULL; window_it = window_it->next) {
			WnckWindow* window;
			window = (WnckWindow*) window_it->data;
			{
				if (wnck_window_get_window_type (window) == WNCK_WINDOW_DESKTOP) {
					WnckWindow* _tmp1_;
					self->priv->_wnck_desktop_window = (_tmp1_ = _g_object_ref0 (window), _g_object_unref0 (self->priv->_wnck_desktop_window), _tmp1_);
				}
			}
		}
	}
	if (self->priv->_wnck_desktop_window != NULL) {
		GnomenuWindow* _tmp2_;
		self->priv->_desktop_window = (_tmp2_ = gnomenu_window_foreign_new (wnck_window_get_xid (self->priv->_wnck_desktop_window)), _g_object_unref0 (self->priv->_desktop_window), _tmp2_);
	} else {
		GnomenuWindow* _tmp3_;
		self->priv->_desktop_window = (_tmp3_ = NULL, _g_object_unref0 (self->priv->_desktop_window), _tmp3_);
	}
}


static gboolean gnomenu_monitor_is_window_on_my_monitor (GnomenuMonitor* self, GnomenuWindow* win) {
	gboolean result = FALSE;
	gint win_num;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	if (self->priv->_per_monitor_mode == FALSE) {
		result = TRUE;
		return result;
	}
	win_num = -1;
	if (win != NULL) {
		win_num = gnomenu_window_get_monitor_num (win);
	}
	if (win_num == (-1)) {
		g_debug ("monitor.vala:156: fallback to use pointer");
		win_num = gnomenu_monitor_get_monitor_num_at_pointer (self);
	}
	if (self->priv->_per_monitor_mode) {
		_tmp2_ = self->priv->_monitor_num != (-1);
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		_tmp1_ = win_num != (-1);
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = win_num != self->priv->_monitor_num;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static void gnomenu_monitor_wnck_status_changed (GnomenuMonitor* self) {
	WnckWindow* wnck_prev;
	WnckWindow* wnck_new;
	g_return_if_fail (self != NULL);
	wnck_prev = _g_object_ref0 (self->priv->_wnck_active_window);
	wnck_new = _g_object_ref0 (wnck_screen_get_active_window (self->priv->_screen));
	if (wnck_new == NULL) {
		WnckWindow* _tmp0_;
		wnck_new = (_tmp0_ = _g_object_ref0 (self->priv->_wnck_desktop_window), _g_object_unref0 (wnck_new), _tmp0_);
	}
	if (wnck_prev == wnck_new) {
		g_signal_emit_by_name (self, "active-window-received-focus");
		_g_object_unref0 (wnck_new);
		_g_object_unref0 (wnck_prev);
		return;
	}
	if (wnck_new != NULL) {
		switch (wnck_window_get_window_type (wnck_new)) {
			case WNCK_WINDOW_NORMAL:
			case WNCK_WINDOW_UTILITY:
			case WNCK_WINDOW_DIALOG:
			case WNCK_WINDOW_DESKTOP:
			{
				break;
			}
			default:
			{
				WnckWindow* _tmp1_;
				wnck_new = (_tmp1_ = _g_object_ref0 (self->priv->_wnck_desktop_window), _g_object_unref0 (wnck_new), _tmp1_);
				break;
			}
		}
	}
	gnomenu_monitor_update_active_window (self, wnck_new);
	_g_object_unref0 (wnck_new);
	_g_object_unref0 (wnck_prev);
}


static void gnomenu_monitor_update_active_window (GnomenuMonitor* self, WnckWindow* from_wnck_window) {
	GnomenuWindow* new;
	g_return_if_fail (self != NULL);
	g_debug ("monitor.vala:198: %p, update_active_window called once", self);
	new = NULL;
	if (from_wnck_window != NULL) {
		GnomenuWindow* _tmp0_;
		new = (_tmp0_ = gnomenu_window_foreign_new (wnck_window_get_xid (from_wnck_window)), _g_object_unref0 (new), _tmp0_);
	} else {
		GnomenuWindow* _tmp1_;
		new = (_tmp1_ = NULL, _g_object_unref0 (new), _tmp1_);
	}
	if (!gnomenu_monitor_is_window_on_my_monitor (self, new)) {
		if (!gnomenu_window_is_on_active_workspace (new)) {
			gnomenu_monitor_replace_active_window (self, self->priv->_desktop_window);
		}
		gnomenu_monitor_replace_dummy_window (self, new);
		if (self->priv->_wnck_active_window_is_closed) {
			gnomenu_monitor_replace_active_window (self, self->priv->_desktop_window);
		}
		g_debug ("monitor.vala:218: %p, not on my monitor", self);
		g_signal_emit_by_name (self, "active-window-lost-focus");
	} else {
		g_debug ("monitor.vala:221: %p, on my monitor", self);
		gnomenu_monitor_replace_dummy_window (self, NULL);
		gnomenu_monitor_replace_active_window (self, new);
	}
	_g_object_unref0 (new);
}


static void _gnomenu_monitor_rebuild_managed_shell_gnomenu_window_menu_context_changed (GnomenuWindow* _sender, gpointer self) {
	gnomenu_monitor_rebuild_managed_shell (self);
}


static void _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed (GnomenuWindow* _sender, gint prev_num, gpointer self) {
	gnomenu_monitor_active_window_moved (self);
}


static void gnomenu_monitor_replace_active_window (GnomenuMonitor* self, GnomenuWindow* new) {
	GnomenuWindow* prev;
	WnckWindow* _tmp0_;
	GnomenuWindow* _tmp3_;
	g_return_if_fail (self != NULL);
	prev = _g_object_ref0 (self->priv->_active_window);
	self->priv->_wnck_active_window = (_tmp0_ = NULL, _g_object_unref0 (self->priv->_wnck_active_window), _tmp0_);
	if (self->priv->_active_window != NULL) {
		guint _tmp1_;
		guint _tmp2_;
		g_signal_parse_name ("menu-context-changed", GNOMENU_TYPE_WINDOW, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_active_window, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _gnomenu_monitor_rebuild_managed_shell_gnomenu_window_menu_context_changed, self);
		g_signal_parse_name ("monitor-num-changed", GNOMENU_TYPE_WINDOW, &_tmp2_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_active_window, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed, self);
	}
	self->priv->_active_window = (_tmp3_ = _g_object_ref0 (new), _g_object_unref0 (self->priv->_active_window), _tmp3_);
	if (self->priv->_active_window != NULL) {
		WnckWindow* _tmp4_;
		self->priv->_wnck_active_window = (_tmp4_ = gnomenu_window_get_wnck_window (self->priv->_active_window), _g_object_unref0 (self->priv->_wnck_active_window), _tmp4_);
		g_signal_connect_object (self->priv->_active_window, "menu-context-changed", (GCallback) _gnomenu_monitor_rebuild_managed_shell_gnomenu_window_menu_context_changed, self, 0);
		g_signal_connect_object (self->priv->_active_window, "monitor-num-changed", (GCallback) _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed, self, 0);
	}
	gnomenu_monitor_rebuild_managed_shell (self);
	g_signal_emit_by_name (self, "active-window-changed", prev);
	_g_object_unref0 (prev);
}


static void gnomenu_monitor_replace_dummy_window (GnomenuMonitor* self, GnomenuWindow* new) {
	WnckWindow* _tmp0_;
	GnomenuWindow* _tmp2_;
	g_return_if_fail (self != NULL);
	self->priv->_wnck_dummy_window = (_tmp0_ = NULL, _g_object_unref0 (self->priv->_wnck_dummy_window), _tmp0_);
	if (self->priv->_dummy_window != NULL) {
		guint _tmp1_;
		g_signal_parse_name ("monitor-num-changed", GNOMENU_TYPE_WINDOW, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_dummy_window, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed, self);
	}
	self->priv->_dummy_window = (_tmp2_ = _g_object_ref0 (new), _g_object_unref0 (self->priv->_dummy_window), _tmp2_);
	if (self->priv->_dummy_window != NULL) {
		WnckWindow* _tmp3_;
		self->priv->_wnck_dummy_window = (_tmp3_ = gnomenu_window_get_wnck_window (self->priv->_dummy_window), _g_object_unref0 (self->priv->_wnck_dummy_window), _tmp3_);
		g_signal_connect_object (self->priv->_dummy_window, "monitor-num-changed", (GCallback) _gnomenu_monitor_active_window_moved_gnomenu_window_monitor_num_changed, self, 0);
	}
}


static void gnomenu_monitor_active_window_moved (GnomenuMonitor* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_dummy_window != NULL) {
		g_debug ("monitor.vala:264: dummy window_moved to life");
		if (gnomenu_monitor_is_window_on_my_monitor (self, self->priv->_dummy_window)) {
			GnomenuWindow* save;
			save = _g_object_ref0 (self->priv->_dummy_window);
			gnomenu_monitor_replace_dummy_window (self, NULL);
			gnomenu_monitor_replace_active_window (self, save);
			_g_object_unref0 (save);
		}
	} else {
		g_debug ("monitor.vala:275: active window_moved to death");
		if (!gnomenu_monitor_is_window_on_my_monitor (self, self->priv->_active_window)) {
			GnomenuWindow* save;
			save = _g_object_ref0 (self->priv->_active_window);
			gnomenu_monitor_replace_active_window (self, self->priv->_desktop_window);
			gnomenu_monitor_replace_dummy_window (self, save);
			_g_object_unref0 (save);
		}
	}
}


static gint gnomenu_monitor_get_monitor_num_at_pointer (GnomenuMonitor* self) {
	gint result = 0;
	GdkScreen* gdk_screen;
	GdkDisplay* display;
	gint x = 0;
	gint y = 0;
	g_return_val_if_fail (self != NULL, 0);
	if (self->priv->_screen == NULL) {
		result = -1;
		return result;
	}
	gdk_screen = gnomenu_monitor_wnck_screen_to_gdk_screen (self->priv->_screen);
	display = _g_object_ref0 (gdk_screen_get_display (gdk_screen));
	gdk_display_get_pointer (display, NULL, &x, &y, NULL);
	result = gdk_screen_get_monitor_at_point (gdk_screen, x, y);
	_g_object_unref0 (display);
	_g_object_unref0 (gdk_screen);
	return result;
}


void gnomenu_monitor_rebuild_shell (GnomenuMonitor* self, GnomenuShell* shell) {
	GError * _inner_error_;
	char* context;
	g_return_if_fail (self != NULL);
	g_return_if_fail (shell != NULL);
	_inner_error_ = NULL;
	gnomenu_shell_set_length (shell, 0);
	if (self->priv->_active_window == NULL) {
		return;
	}
	context = gnomenu_window_get_menu_context (self->priv->_active_window);
	if (context == NULL) {
		_g_free0 (context);
		return;
	}
	{
		gnomenu_parser_parse (shell, context, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_critical ("monitor.vala:310: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_free0 (context);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (context);
}


static void gnomenu_monitor_rebuild_managed_shell (GnomenuMonitor* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_managed_shell == NULL) {
		return;
	}
	gnomenu_monitor_rebuild_shell (self, self->priv->_managed_shell);
	g_signal_emit_by_name (self, "shell-rebuilt");
}


static void _gnomenu_monitor_on_window_opened_wnck_screen_window_opened (WnckScreen* _sender, WnckWindow* window, gpointer self) {
	gnomenu_monitor_on_window_opened (self, _sender, window);
}


static void _gnomenu_monitor_on_window_closed_wnck_screen_window_closed (WnckScreen* _sender, WnckWindow* window, gpointer self) {
	gnomenu_monitor_on_window_closed (self, _sender, window);
}


static void _gnomenu_monitor_on_active_window_changed_wnck_screen_active_window_changed (WnckScreen* _sender, WnckWindow* previous_window, gpointer self) {
	gnomenu_monitor_on_active_window_changed (self, _sender, previous_window);
}


static void gnomenu_monitor_detach_from_screen (GnomenuMonitor* self) {
	WnckWindow* _tmp3_;
	WnckWindow* _tmp4_;
	WnckWindow* _tmp5_;
	g_return_if_fail (self != NULL);
	if (self->priv->_screen != NULL) {
		guint _tmp0_;
		guint _tmp1_;
		guint _tmp2_;
		g_signal_parse_name ("window-opened", WNCK_TYPE_SCREEN, &_tmp0_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_screen, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _gnomenu_monitor_on_window_opened_wnck_screen_window_opened, self);
		g_signal_parse_name ("window-closed", WNCK_TYPE_SCREEN, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_screen, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _gnomenu_monitor_on_window_closed_wnck_screen_window_closed, self);
		g_signal_parse_name ("active-window-changed", WNCK_TYPE_SCREEN, &_tmp2_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (self->priv->_screen, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _gnomenu_monitor_on_active_window_changed_wnck_screen_active_window_changed, self);
	}
	self->priv->_wnck_desktop_window = (_tmp3_ = NULL, _g_object_unref0 (self->priv->_wnck_desktop_window), _tmp3_);
	self->priv->_wnck_dummy_window = (_tmp4_ = NULL, _g_object_unref0 (self->priv->_wnck_dummy_window), _tmp4_);
	self->priv->_wnck_active_window = (_tmp5_ = NULL, _g_object_unref0 (self->priv->_wnck_active_window), _tmp5_);
}


static void gnomenu_monitor_attach_to_screen (GnomenuMonitor* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_screen != NULL) {
		wnck_screen_force_update (self->priv->_screen);
		g_signal_connect_object (self->priv->_screen, "window-closed", (GCallback) _gnomenu_monitor_on_window_closed_wnck_screen_window_closed, self, 0);
		g_signal_connect_object (self->priv->_screen, "window-opened", (GCallback) _gnomenu_monitor_on_window_opened_wnck_screen_window_opened, self, 0);
		g_signal_connect_object (self->priv->_screen, "active-window-changed", (GCallback) _gnomenu_monitor_on_active_window_changed_wnck_screen_active_window_changed, self, 0);
		gnomenu_monitor_update_desktop_window (self);
		gnomenu_monitor_wnck_status_changed (self);
	}
}


GnomenuShell* gnomenu_monitor_get_managed_shell (GnomenuMonitor* self) {
	GnomenuShell* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_managed_shell;
	return result;
}


void gnomenu_monitor_set_managed_shell (GnomenuMonitor* self, GnomenuShell* value) {
	GnomenuShell* _tmp0_;
	g_return_if_fail (self != NULL);
	if (self->priv->_managed_shell != NULL) {
		g_object_set_data_full ((GObject*) self->priv->_managed_shell, "globalmenu-monitor", NULL, NULL);
	}
	self->priv->_managed_shell = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_managed_shell), _tmp0_);
	if (self->priv->_managed_shell != NULL) {
		g_object_set_data_full ((GObject*) self->priv->_managed_shell, "globalmenu-monitor", _g_object_ref0 (self), g_object_unref);
	}
	gnomenu_monitor_rebuild_managed_shell (self);
	g_object_notify ((GObject *) self, "managed-shell");
}


gint gnomenu_monitor_get_monitor_num (GnomenuMonitor* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_monitor_num;
	return result;
}


void gnomenu_monitor_set_monitor_num (GnomenuMonitor* self, gint value) {
	g_return_if_fail (self != NULL);
	if (self->priv->_monitor_num != value) {
		self->priv->_monitor_num = value;
		gnomenu_monitor_active_window_moved (self);
	}
	g_object_notify ((GObject *) self, "monitor-num");
}


gboolean gnomenu_monitor_get_per_monitor_mode (GnomenuMonitor* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_per_monitor_mode;
	return result;
}


void gnomenu_monitor_set_per_monitor_mode (GnomenuMonitor* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_per_monitor_mode = value;
	g_object_notify ((GObject *) self, "per-monitor-mode");
}


GnomenuWindow* gnomenu_monitor_get_active_window (GnomenuMonitor* self) {
	GnomenuWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_active_window;
	return result;
}


static void gnomenu_monitor_set_active_window (GnomenuMonitor* self, GnomenuWindow* value) {
	GnomenuWindow* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_active_window = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_active_window), _tmp0_);
	g_object_notify ((GObject *) self, "active-window");
}


static void gnomenu_monitor_class_init (GnomenuMonitorClass * klass) {
	gnomenu_monitor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GnomenuMonitorPrivate));
	G_OBJECT_CLASS (klass)->dispose = gnomenu_monitor_real_dispose;
	G_OBJECT_CLASS (klass)->get_property = gnomenu_monitor_get_property;
	G_OBJECT_CLASS (klass)->set_property = gnomenu_monitor_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnomenu_monitor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_MONITOR_MANAGED_SHELL, g_param_spec_object ("managed-shell", "managed-shell", "managed-shell", GNOMENU_TYPE_SHELL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_MONITOR_MONITOR_NUM, g_param_spec_int ("monitor-num", "monitor-num", "monitor-num", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_MONITOR_PER_MONITOR_MODE, g_param_spec_boolean ("per-monitor-mode", "per-monitor-mode", "per-monitor-mode", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNOMENU_MONITOR_ACTIVE_WINDOW, g_param_spec_object ("active-window", "active-window", "active-window", GNOMENU_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("active_window_changed", GNOMENU_TYPE_MONITOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, GNOMENU_TYPE_WINDOW);
	g_signal_new ("shell_rebuilt", GNOMENU_TYPE_MONITOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("active_window_lost_focus", GNOMENU_TYPE_MONITOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("active_window_received_focus", GNOMENU_TYPE_MONITOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void gnomenu_monitor_instance_init (GnomenuMonitor * self) {
	self->priv = GNOMENU_MONITOR_GET_PRIVATE (self);
	self->priv->_monitor_num = -1;
	self->priv->_dummy_window = NULL;
	self->priv->_desktop_window = NULL;
	self->priv->_screen = NULL;
	self->priv->_wnck_desktop_window = NULL;
	self->priv->_wnck_active_window = NULL;
	self->priv->_wnck_dummy_window = NULL;
	self->priv->disposed = FALSE;
	self->priv->_wnck_active_window_is_closed = FALSE;
}


static void gnomenu_monitor_finalize (GObject* obj) {
	GnomenuMonitor * self;
	self = GNOMENU_MONITOR (obj);
	_g_object_unref0 (self->priv->_managed_shell);
	_g_object_unref0 (self->priv->_active_window);
	_g_object_unref0 (self->priv->_dummy_window);
	_g_object_unref0 (self->priv->_desktop_window);
	_g_object_unref0 (self->priv->_screen);
	_g_object_unref0 (self->priv->_wnck_desktop_window);
	_g_object_unref0 (self->priv->_wnck_active_window);
	_g_object_unref0 (self->priv->_wnck_dummy_window);
	G_OBJECT_CLASS (gnomenu_monitor_parent_class)->finalize (obj);
}


GType gnomenu_monitor_get_type (void) {
	static volatile gsize gnomenu_monitor_type_id__volatile = 0;
	if (g_once_init_enter (&gnomenu_monitor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GnomenuMonitorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnomenu_monitor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GnomenuMonitor), 0, (GInstanceInitFunc) gnomenu_monitor_instance_init, NULL };
		GType gnomenu_monitor_type_id;
		gnomenu_monitor_type_id = g_type_register_static (G_TYPE_OBJECT, "GnomenuMonitor", &g_define_type_info, 0);
		g_once_init_leave (&gnomenu_monitor_type_id__volatile, gnomenu_monitor_type_id);
	}
	return gnomenu_monitor_type_id__volatile;
}


static void gnomenu_monitor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GnomenuMonitor * self;
	self = GNOMENU_MONITOR (object);
	switch (property_id) {
		case GNOMENU_MONITOR_MANAGED_SHELL:
		g_value_set_object (value, gnomenu_monitor_get_managed_shell (self));
		break;
		case GNOMENU_MONITOR_MONITOR_NUM:
		g_value_set_int (value, gnomenu_monitor_get_monitor_num (self));
		break;
		case GNOMENU_MONITOR_PER_MONITOR_MODE:
		g_value_set_boolean (value, gnomenu_monitor_get_per_monitor_mode (self));
		break;
		case GNOMENU_MONITOR_ACTIVE_WINDOW:
		g_value_set_object (value, gnomenu_monitor_get_active_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void gnomenu_monitor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GnomenuMonitor * self;
	self = GNOMENU_MONITOR (object);
	switch (property_id) {
		case GNOMENU_MONITOR_MANAGED_SHELL:
		gnomenu_monitor_set_managed_shell (self, g_value_get_object (value));
		break;
		case GNOMENU_MONITOR_MONITOR_NUM:
		gnomenu_monitor_set_monitor_num (self, g_value_get_int (value));
		break;
		case GNOMENU_MONITOR_PER_MONITOR_MODE:
		gnomenu_monitor_set_per_monitor_mode (self, g_value_get_boolean (value));
		break;
		case GNOMENU_MONITOR_ACTIVE_WINDOW:
		gnomenu_monitor_set_active_window (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




